### ISSUE TITLE
edit编辑无效

### ISSUE THREAD

**Issue by xuefliang** [ywb94/openwrt-ssr#10]
从1.1.2升级到1.1.4 ar71xx版本，客户端和服务器端edit无效，无法进行编辑。

**Comment by ywb94** [comment]
奇怪，我这里的ar71xx没有问题，你卸载重装或重启试试，路由器固件版本是多少、有无错误提示？

**Comment by xuefliang** [comment]
Chaos Calmer 15.05.1,我重装看看，没有任何错误提示，delete可用，就edit没有弹出编辑框。

**Comment by xuefliang** [comment]
重启路由器以后就好了！
