### ISSUE TITLE
BB版sdk编译出现ipset错误

### ISSUE THREAD

**Issue by crackself** [ywb94/openwrt-ssr#100]
ipset-6.20.1/.configured_] Error 1
请问该如何解决呢？

**Comment by crackself** [comment]
全部输出：
configure: error: Invalid kernel source directory /lib/modules/2.6.32-042stab120.20/source
make[2]: *** [/home/crackself/openwrt-sdk/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/linux-ramips_mt7620/ipset-6.20.1/.configured_] Error 1
make[2]: Leaving directory `/home/crackself/openwrt-sdk/package/network/utils/ipset'
make[1]: *** [package/network/utils/ipset/compile] Error 2
make[1]: Leaving directory `/home/crackself/openwrt-sdk'
make: *** [package/openwrt-ssr/compile] Error 2

**Comment by daofeng2015** [comment]
2.6的内核。。。。。。
