### ISSUE TITLE
gfw模式需要这样配置才能连谷歌

### ISSUE THREAD

**Issue by RoweV194** [ywb94/openwrt-ssr#101]
当时没考虑别人不是x86路由器,变砖了只能抱歉了,下面很详细,请往下看

**Comment by RoweV194** [comment]
我的固件是LEDE 17.01.1 X86_64

**Comment by daniuer** [comment]
作者介绍过如下，所以必须在dnsmasq.conf里用 conf-dir=/etc/dnsmasq.ssr这一句指定解析dnsmasq.ssr目录里的GFW文件才能使用GFW功能。
1、GFW列表存放在/etc/dnsmasq.ssr/gfw_list.conf，如要自定义GFW规则，在目录/etc/dnsmasq.ssr下创建一个文件，名称任取，比如myrules.conf
在文件中按要求输入你需要添加的网址，比如要添加google.com.hk，需输入如下两行：
server=/.google.com.hk/127.0.0.1#5353
ipset=/.google.com.hk/gfwlist
添加后/etc/init.d/dnsmasq restart重启dnsmasq
用户添加的文件在数据更新或版本升级时不会被覆盖
2、IP网段文件存放在/etc/china_ssr.txt，可以在此文件中添加需要的IP，此文件在数据更新或版本升级时会覆盖，需提前备份用户数据。

**Comment by dj3260** [comment]
非常感谢楼上的回答，我也是ip路由模式正常，GFW模式无法翻墙，我知道原因是DNS解析的问题，但是怎么解决毫无头绪。晚上回家就按照楼上的方法试试看。

**Comment by November-raining** [comment]
感谢楼上的楼上解答
dns配置这里 GFW走127.0.0.1#5353传递到ssr后目前ipk就两条路走：
1.要么继续转到vps的udp端口解析。2.或者走作者提供的pdnsd进行tcp解析
不过现在到ssr后我想走cdns解析(例如cdns配置好监听地址端口:127.0.0.1#5300)。
但是ssr  luci界面好像没法配置过去。

**Comment by daniuer** [comment]
作者一再强调过，一定要SS服务器支持udp转发。恩山作者的互动发布帖里教程写得较为详细http://www.right.com.cn/forum/forum.php?mod=viewthread&tid=204802&mobile=2

**Comment by November-raining** [comment]
我想既然可以到pdnsd做tcp解析，应该也可转发到其他应用如cdns dnsforwarder上解析，
而且到服务器也是解析转发到vps上，小白不清楚IP路由模式可以，GFW就不行了

**Comment by daniuer** [comment]
我也是小白，该作者的客户端我只会根据说明使用，无法更深一步的对你的要求提供帮助，见谅！

**Comment by sosmygirl** [comment]
@RoweV194 ps -w 看到的dnsmasq -c /var/etc/dnsmasq.conf。我像你那么修改后，LAN的ip都不能获取了

**Comment by RoweV194** [comment]
你的路由器变砖了?

**Comment by sosmygirl** [comment]
没有，就是在openwrt bb版上gfw模式怎么都不成功。我换其他固件都行（斐讯k2p官改，pandavn）

**Comment by mc-linhx** [comment]
/etc/init.d/shadowsocksr 文件里面从400行开始，改成如下 就可以了：

`	if  [ -z "$gfw_enable" ] ;then
	case "$(uci_get_by_type global tunnel_enable)" in
		1|on|true|yes|enabled)
			start_tunnel
			mkdir -p /tmp/dnsmasq.d
			cat > /tmp/dnsmasq.d/dnsmasq-ssr.conf <<EOF
conf-dir=/etc/dnsmasq.ssr
EOF
			/etc/init.d/dnsmasq restart
			;;
	esac
	else
	mkdir -p /tmp/dnsmasq.d
	cat > /tmp/dnsmasq.d/dnsmasq-ssr.conf <<EOF
conf-dir=/etc/dnsmasq.ssr
EOF
	/etc/init.d/dnsmasq restart
	fi`

**Comment by ibq00** [comment]
看下你的dnsmasq是不是fll版本

**Comment by CcAi0** [comment]
@mc-linhx 我的版本是“luci-app-shadowsocksR-GFW_1.2.4_all”，/etc/init.d/shadowsocksr  文件没有400行，总共只有367行，能否告知一下，你所说的修改，是在什么原代码上进行的

**Comment by CcAi0** [comment]
@daniuer 我将dnsmasq.conf里原来的“conf-dir=/tmp/dnsmasq.d”，该为了“ conf-dir=/etc/dnsmasq.ssr”，但是保存后，要不了一会儿，修改后的dnsmasq.conf文件里“ conf-dir=/etc/dnsmasq.ssr”这行后就会被自动追加一行“conf-dir=/tmp/dnsmasq.d”，然后还是使用不了GFW模式...

**Comment by CcAi0** [comment]
@ibq00 确认dnsmasq是dnsmasq-full版本，版本号为2.78-6

**Comment by 770057966** [comment]
Thanks, you. Amazing
