### ISSUE TITLE
编译错误，缺少libz.so.1

### ISSUE THREAD

**Issue by 467815891a** [ywb94/openwrt-ssr#13]
最新版的LEDE，编译时已经勾选了zlib了，可是依旧报错
install -m0755 ./files/shadowsocksr.init /home/wei/LEDE/build_dir/target-arm_xscale_musl-1.1.15_eabi/openwrt-ssr/openssl/openwrt-ssr-1.1.5/ipkg-all/luci-app-shadowsocksR-Client/etc/init.d/shadowsocksr
find /home/wei/LEDE/build_dir/target-arm_xscale_musl-1.1.15_eabi/openwrt-ssr/openssl/openwrt-ssr-1.1.5/ipkg-all/luci-app-shadowsocksR-Client -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
Package luci-app-shadowsocksR-Client is missing dependencies for the following libraries:
libz.so.1

**Comment by ywb94** [comment]
试试：
sudo apt-get install libz-dev

**Comment by 467815891a** [comment]
我用的是fedora25，已经安装过zlib-devel了
/sbin/ldconfig -v | grep libz.so.1
	libz.so.1 -> libz.so.1.2.8
	libz.so.1 -> libz.so.1

**Comment by 467815891a** [comment]
在makefile里面添加了+zlib，就过了
