### ISSUE TITLE
LEDE编译求助

### ISSUE THREAD

**Issue by goodryb** [ywb94/openwrt-ssr#130]
LEDE上好像没有现成的包可以用，所以想按照教程自己编译一个，现在遇到个问题
make menuconfig
make -s -C scripts/config all CC=cc: build failed. Please re-run make with -j1 V=s to see what's going on
make: *** [scripts/config/mconf] Error 1

**Comment by ctw8989** [comment]
git clone https://github.com/shadowsocksr-backup/shadowsocksr-libev.git package/feeds/packages/shadowsocksR-libev
git clone https://github.com/lhp7895/luci-app-shadowsocksr-20170728.git package/feeds/luci/luci-app-shadowsocksR
