### ISSUE TITLE
依赖ip和ip-full冲突

### ISSUE THREAD

**Issue by lightpencil** [ywb94/openwrt-ssr#14]
ip和ip-full冲突，强行卸载ip-full后服务端无法使用。

**Comment by daniuer** [comment]
我遇到了同样问题，我使用明月固件，强行在系统—文件传输功能里上传安装后，可以正常使用了。

**Comment by daniuer** [comment]
在软件包里卸载ip-full后，
opkg update
opkg install ip
或者下载IP，http://downloads.openwrt.org/chaos_calmer/15.05.1/ar71xx/generic/packages/base/ip_4.0.0-1_ar71xx.ipk
上传至路由器安装。

**Comment by EasyingFreeman** [comment]
还有一个方法 强制安装/强制覆盖安装
opkg --force-depends --force-overwrite install
亲测可行

**Comment by huaxianyan** [comment]
我强制安装之后，发现安装成功，配置也配置好了

但是发现内网控制压根不生效，不管列表内列表外怎么搞都没法让设备走代理

打算试试卸载IP-full重新安装看看

**Comment by cym422948** [comment]
实测明月固件ip-full卸载后再安装成功升级1.21
