### ISSUE TITLE
谷歌连通性检查ok，ipset也正常写入ip，就是翻不过gfw

### ISSUE THREAD

**Issue by Hefeeder** [ywb94/openwrt-ssr#147]
gfw列表也更新了，路由器，pc机dns解析都正常。。但是都ping不通google，help。。。

**Comment by yearnsun** [comment]
尽量选用ip模式,我用gfw也是不能用,编译时尽量不要选gfw模式

**Comment by Hefeeder** [comment]
我下错openwrt的版本了。。

**Comment by 275761919** [comment]
gfw模式不能用还和固件版本有关吗，我的是lede17.01，也是gfw模式不能使用，ip模式正常

**Comment by Hefeeder** [comment]
openwrt-15.05.1-x86-64-rootfs-ext4.img.gz 这个版本我用不了gfw模式 换成openwrt-15.05.1-x86-64-combined-ext4.img.gz 后就能用了
