### ISSUE TITLE
使用后Telegram Android端无法发图和视频。

### ISSUE THREAD

**Issue by daniuer** [ywb94/openwrt-ssr#15]
如题，两部手机均如此，PC端不受影响。之前手机用SSR客户端能正常发图和视频。这是什么原因导致的呢？

**Comment by haruhitamako** [comment]
手机端dns污染，可以考虑安装chinadns增强解析

**Comment by daniuer** [comment]
谢谢，原来如此，那在大大你的这个软件界面里，哪里可以集成进去呢？OP里已经集成了chinadns。

**Comment by haruhitamako** [comment]
你搞错了，我不是作者。op集成的chinadns可以直接设置好就能使用，你可以去飞羽博客找一下相关的文章。

**Comment by daniuer** [comment]
飞羽博客一直有去，不过我开启了chinadns后这个问题依旧，很奇怪。

**Comment by haruhitamako** [comment]
上游试试114.114.114.114,208.67.222.222#443

**Comment by daniuer** [comment]
还是不行，好奇怪的问题。

**Comment by ywb94** [comment]
本版本没有对dns进行处理，dns在本地都是被污染的，发到对端SSR重新解析，不过由于被污染的域名IP是随机的，有可能给一个国内IP，就发不到远端了。
下一分支版本支持GFWList，彻底解决DNS污染问题。

**Comment by daniuer** [comment]
原来是这个原因，不过启动了chinadns以后问题依旧，可能是我设置有问题。
非常期待大大的下个版本，你开发的OP-SSR比我之前用过的两个版本更快更好操作。

**Comment by haruhitamako** [comment]
dhcp里要设置127.0.0.1#chinadns监视端口，同时勾选忽略解析。注意的是要把忽略解析下面的路径记录好，否则以后不用chinadns就无法上网了

**Comment by daniuer** [comment]
难怪呢，我按照飞羽的教程设置好chinadns监视端口以后，手机上依然有这个问题，然后我直接关闭了chinadns重启路由器后就无法上网，连网关都打不开，只能恢复路由器，这一点在我看的好多教程里都没提到，还好大大你提醒我了。

**Comment by ywb94** [comment]
V1.1.6版本已支持gfwlist模式

**Comment by daniuer** [comment]
好的，我去下载试试。

**Comment by ywb94** [comment]
系统中存在dnsmasq-full是不会再安装的，你说的错误提示是不是配置文件的冲突提示，将冲突文件改名就行了

**Comment by ywb94** [comment]
对

**Comment by daniuer** [comment]
搞定了，非常感谢你的耐心指导。晚上使用后我再来反馈Telegram Android端是否可以上传图片和视频。

**Comment by daniuer** [comment]
经测试Telegram Android端用gfwlist模式完全连接不上，而用IP路由模式可以正常连接不过视频图片无法发送，跟以前一样。是不是需要把Telegram的IP加入路由器的gfwlist列表呢？gfwlist的路径在哪里呢？

**Comment by ywb94** [comment]
是不是用的是udp，把udp中继服务器打开

**Comment by daniuer** [comment]
udp中继服务器是打开了，查了下网上的反馈，

**Comment by daniuer** [comment]
添加自定义IP段后，今天发图正常了。
