### ISSUE TITLE
LEDE 无法启动客户端

### ISSUE THREAD

**Issue by loshine** [ywb94/openwrt-ssr#156]
路由器型号：NETGEAR WNDR4300
固件版本： LEDE Reboot 17.01.4 r3560-79f57e422d / LuCI lede-17.01 branch (git-17.290.79498-d3f0685) 
内核版本：4.4.92

情况1： 直接使用本项目编译好的 ipk，无法启动客户端，百度、谷歌连通性检查无法通过，无法更新【国内IP段】数据库，【服务器端口】检查通过
情况2：使用 lede sdk 编译本项目，路由器无法自动分配 IP
情况3：使用 lede sdk 和  [lededev](https://github.com/lededev/openwrt-ssr) 分支编译，百度、谷歌连通性检查无法通过，能够更新【国内IP段】数据库，【服务器端口】检查通过

进入`/usr/bin`

<img width="831" alt="jietu20171126-111352" src="https://user-images.githubusercontent.com/11252444/33236835-f2f9e626-d29a-11e7-9bb2-0835fa340a21.png">

直接运行 ssr-local

<img width="383" alt="jietu20171126-111524" src="https://user-images.githubusercontent.com/11252444/33236839-2022d702-d29b-11e7-9e03-2e02d8250275.png">

**Comment by loshine** [comment]
我自己的问题。。

**Comment by WeiMXi** [comment]
请问是什么问题，我出现了和你类似的情况，不知道该如何解决。

**Comment by loshine** [comment]
@WeiMXi

**Comment by WeiMXi** [comment]
不管怎样谢谢了，我是Openwrt 18.06 交叉编译安装了[https://github.com/daiaji/openwrt-ssr](url)这个SSR GWF版本，但是百度、谷歌连通性检查无法通过，能够更新【国内IP段】数据库，【服务器端口】检查通过，IP也不能分配，现在确定应该是依赖项dnsmasq-full 的问题，dnsmasq-full启动总是报错，显示` relocation error: /usr/sbin/dnsmasq: symbol nettle_get_hashes`，现在安装回dnsmasq就好了，这好像是dnsmasq-full的一个BUG[https://bugzilla.redhat.com/show_bug.cgi?id=1556888](url)，只能是先卸载了，改天交叉编译一个IP分流不依赖dnsmasq-full的SSR用吧
