### ISSUE TITLE
access control problem

### ISSUE THREAD

**Issue by hanlray** [ywb94/openwrt-ssr#16]
I want to prevent the local processes running on the openwrt itself to use the SS service. I tried to add the lan ip of openwrt (192.168.1.1) to the "LAN Host List" under "Interfaces LAN", but it does not work (still use the SS service). Other lan IPs do work. Is there a way to work in this case?
BTW, great work, thank you.

**Comment by ywb94** [comment]
ok，V1.1.7 support

**Comment by ywb94** [comment]
V1.1.7 have released.
Use "Access control-Interface LAN-Router Proxy"

**Comment by hanlray** [comment]
works. Great! Thanks.
