### ISSUE TITLE
打开luci报错

### ISSUE THREAD

**Issue by CQUHCA** [ywb94/openwrt-ssr#165]
安装好后打开界面出现/usr/lib/lua/luci/dispatcher.lua:487: Failed to execute function dispatcher target for entry '/admin/services/shadowsocksr'.
The called action terminated with an exception:
/usr/lib/lua/luci/dispatcher.lua:487: Failed to execute arcombine dispatcher target for entry '/admin/services/shadowsocksr/client'.
The called action terminated with an exception:
/usr/lib/lua/luci/model/cbi/shadowsocksr/client.lua:26: attempt to call field 'arptable' (a nil value)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:487: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:121: in function </usr/lib/lua/luci/dispatcher.lua:120>
报错信息提示我们错误在/usr/lib/lua/luci/model/cbi/shadowsocksr/client.lua:26。/usr/lib/lua/luci/model/cbi/shadowsocksr/client.lua 的第26行代码。用vi或者vim打开该文件后找到26行，看到有arptable。于是将local arp_table = luci.sys.net.arptable() or {}修改为local arp_table = luci.ip.neighbors()。同理修改/usr/lib/lua/luci/model/cbi/shadowsocksr/目录下的另一client-config.lua文件相同位置即可。之后配置好客户端就可以愉快的**

**Comment by honeymoe** [comment]
遇到同样问题，保持关注。
推测是编译版本问题……

**Comment by CQUHCA** [comment]
已解决，之前没有注意到已经有道友遇到这个问题了，在第二页“lede编译后，打开界面报错”，需要改两个文件的内容。

**Comment by fuyuxiang0271** [comment]
感谢~~ 改过以后好了~~~

**Comment by 805447391** [comment]
http://www.right.com.cn/forum/thread-251201-1-1.html
解决方案在这。

**Comment by 805447391** [comment]
另一种解决方案：移植PandoraBox的http.lua

**Comment by XiGou** [comment]
解决了 马克

**Comment by laijirong** [comment]
成功解决：）

**Comment by AmadeusGhost** [comment]
解决了，谢谢。

**Comment by ismdeep** [comment]
解决了，谢谢。
