### ISSUE TITLE
纯ipv6环境连接ipv6的SSR会无法使用

### ISSUE THREAD

**Issue by Gahon1995** [ywb94/openwrt-ssr#173]
如果先正常用ipv4连接网络，在连接ssr，能够正常使用，但是如果不连的话就无法连接了
自己猜测的话可能是DNS的问题，但是在SSR那个地方设置DNS为ipv6的也还是不能够连接，不知道什么问题，电脑上纯ipv6就能够正常使用

**Comment by Gahon1995** [comment]
使用ipv6地址就好了

**Comment by XiGou** [comment]
> 使用ipv6地址就好了

我现在也遇到这个问题，能够ping通服务器（v6），ssr连不上，纯v6环境，不知道怎么解决

**Comment by XiGou** [comment]
> 使用ipv6地址就好了

如果看到希望回复，想了解一下你的ssr能否正常使用ipv6，谢谢

**Comment by Gahon1995** [comment]
主要原因应该是不能够通过DNS服务器解析ipv6地址，所以需要服务器ip填写为其ipv6地址，或者先通过ipv4连接，等连接上以后再断开。
