### ISSUE TITLE
for LEDE，编译错误 zlib header files not found

### ISSUE THREAD

**Issue by Copox** [ywb94/openwrt-ssr#20]
于lede brcm2710 sdk；ubuntu 15.10 x64
已经安装了zlib1g-dev 可是在编译sever版的时候 出现错误 “zlib header files not found”
寻求解决办法

**Comment by ywb94** [comment]
修改makefile，加上zlib
Package/luci-app-shadowsocksR = $(call Package/openwrt-ssr/Default,openssl,(OpenSSL),+libopenssl +libpthread +ipset +ip +iptables-mod-tproxy +libpcre +zlib)
Package/luci-app-shadowsocksR-Client = $(call Package/openwrt-ssr/Default,openssl,(OpenSSL),+libopenssl +libpthread +ipset +ip +iptables-mod-tproxy +libpcre +zlib)
Package/luci-app-shadowsocksR-Server = $(call Package/openwrt-ssr/Default,openssl,(OpenSSL),+libopenssl +libpthread +ipset +ip +iptables-mod-tproxy +libpcre +zlib)

**Comment by Copox** [comment]
谢谢作者如此迅速回答
本人在已经在clone回来的makefile 单独针对server版添加“+zlib”了 结果仍然not found

**Comment by ywb94** [comment]
运行：
./scripts/feeds update
./scripts/feeds install zlib
./scripts/feeds install libopenssl

然后重新编译

**Comment by Copox** [comment]
问题解决 lede平台请于SDK中运行
./scripts/feeds update
./scripts/feeds install zlib
./scripts/feeds install libopenssl
./scripts/feeds install libpcre

**Comment by WeiqiChenCN** [comment]
遇到相同的问题：

```
weiqi@B85i-PC:~/lede/sdk$ ./scripts/feeds  install zlib libopenssl
Ignoring feed 'luci' - index missing
Installing package 'zlib' from base
Installing package 'openssl' from base
weiqi@B85i-PC:~/lede/sdk$ make -j1 V=s
checking for library containing floor... none required
checking for thread local storage (TLS) class... __thread
checking zlib.h usability... no
checking zlib.h presence... no
checking for zlib.h... no
configure: error: "zlib header files not found."
Makefile:248: recipe for target '/home/weiqi/lede/sdk/build_dir/target-arm_cortex-a7+neon-vfpv4_musl-1.1.16_eabi/openwrt-ssr/openssl/openwrt-ssr-1.2.1/.configured_yyny' failed
make[3]: *** [/home/weiqi/lede/sdk/build_dir/target-arm_cortex-a7+neon-vfpv4_musl-1.1.16_eabi/openwrt-ssr/openssl/openwrt-ssr-1.2.1/.configured_yyny] Error 1
make[3]: Leaving directory '/home/weiqi/lede/sdk/package/openwrt-ssr'
package/Makefile:105: recipe for target 'package/openwrt-ssr/compile' failed
make[2]: *** [package/openwrt-ssr/compile] Error 2
make[2]: Leaving directory '/home/weiqi/lede/sdk'
package/Makefile:101: recipe for target '/home/weiqi/lede/sdk/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl-1.1.16_eabi/stamp/.package_compile' failed
make[1]: *** [/home/weiqi/lede/sdk/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl-1.1.16_eabi/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/weiqi/lede/sdk'
/home/weiqi/lede/sdk/include/toplevel.mk:191: recipe for target 'world' failed
make: *** [world] Error 2

```


LEDE sdk 下载自：//downloads.lede-project.org/releases/17.01.4/targets/brcm2708/bcm2709/lede-sdk-17.01.4-brcm2708-bcm2709_gcc-5.4.0_musl-1.1.16_eabi.Linux-x86_64.tar.xz
