### ISSUE TITLE
编译OPENWRT，打开SSR出现错误，有一样的吗？

### ISSUE THREAD

**Issue by xzyd888** [ywb94/openwrt-ssr#213]
Failed to execute arcombine dispatcher target for entry '/admin/services/shadowsocksr/client'.
The called action terminated with an exception:
/usr/lib/lua/luci/model/cbi/shadowsocksr/client.lua:7: module 'luci.model.ipkg' not found:
	no field package.preload['luci.model.ipkg']
	no file './luci/model/ipkg.lua'
	no file '/usr/share/lua/luci/model/ipkg.lua'
	no file '/usr/share/lua/luci/model/ipkg/init.lua'
	no file '/usr/lib/lua/luci/model/ipkg.lua'
	no file '/usr/lib/lua/luci/model/ipkg/init.lua'
	no file './luci/model/ipkg.so'
	no file '/usr/lib/lua/luci/model/ipkg.so'
	no file '/usr/lib/lua/loadall.so'
	no file './luci.so'
	no file '/usr/lib/lua/luci.so'
	no file '/usr/lib/lua/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/lib/lua/luci/model/cbi/shadowsocksr/client.lua:7: in function 'func'
	/usr/lib/lua/luci/cbi.lua:66: in function 'load'
	/usr/lib/lua/luci/dispatcher.lua:863: in function 'target'
	/usr/lib/lua/luci/dispatcher.lua:981: in function </usr/lib/lua/luci/dispatcher.lua:977>

**Comment by puinaam** [comment]
我也是这样 不知道哪里出问题了

**Comment by xzyd888** [comment]
no file './luci/model/ipkg.lua'，补上即可。
