### ISSUE TITLE
希望可以添加一些kcptun的参数选项

### ISSUE THREAD

**Issue by 467815891a** [ywb94/openwrt-ssr#22]
感觉光有端口密码这些还不够，加密方式和mode也很重要啊，手动添加参数比较麻烦，还有mtu，sndwnd，rcvwnd也一起加上吧😂。另外，我经常使用路由器挂BT，所以我希望SSR能够有本机代理的选择，可以选择路由器是直连还是代理，这样就好了。感谢作者的辛勤维护，谢谢

**Comment by ywb94** [comment]
挂BT的话，开GFW模式不就可以了么？

**Comment by ywb94** [comment]
下一版本支持

**Comment by 467815891a** [comment]
十分感谢！

**Comment by ywb94** [comment]
V1.1.7已发布，在“访问控制-接口 LAN”增加了“路由器访问控制”

kcptun暂不增加参数选项，因为kcptun很多参数都是有缺省设置

**Comment by 467815891a** [comment]
1.1.7貌似不能开启kcptun了？kcptun版本号可以检测到，我自己手动也可运行/usr/bin/ssr-kcptun，以前的版本也没有问题啊,不知道可能是什么问题

**Comment by ywb94** [comment]
手滑改错了。下个版本修正
不过此版本打开进程监控的话，30秒后kcptun也会自动起来

**Comment by 467815891a** [comment]
现在OK了，完美😀
