### ISSUE TITLE
LEDE编译报错

### ISSUE THREAD

**Issue by GuangX3** [ywb94/openwrt-ssr#23]
按照LEDE的编译方法，使用如下SDK：

ftp://mirror.0x.sg/lede/snapshots/targets/bcm53xx/generic/lede-sdk-bcm53xx_gcc-5.4.0_musl-1.1.15_eabi.Linux-x86_64.tar.xz

最后出现此错误，即使chmod 777 lede的目录也不行

Signing package index...
Cannot open file '/root/lede-sdk-bcm53xx_gcc-5.4.0_musl-1.1.15_eabi.Linux-x86_64/key-build' for reading
Cannot open file '/root/lede-sdk-bcm53xx_gcc-5.4.0_musl-1.1.15_eabi.Linux-x86_64/key-build' for reading
Cannot open file '/root/lede-sdk-bcm53xx_gcc-5.4.0_musl-1.1.15_eabi.Linux-x86_64/key-build' for reading
Cannot open file '/root/lede-sdk-bcm53xx_gcc-5.4.0_musl-1.1.15_eabi.Linux-x86_64/key-build' for reading
Cannot open file '/root/lede-sdk-bcm53xx_gcc-5.4.0_musl-1.1.15_eabi.Linux-x86_64/key-build' for reading
Cannot open file '/root/lede-sdk-bcm53xx_gcc-5.4.0_musl-1.1.15_eabi.Linux-x86_64/key-build' for reading
Cannot open file '/root/lede-sdk-bcm53xx_gcc-5.4.0_musl-1.1.15_eabi.Linux-x86_64/key-build' for reading
package/Makefile:87: recipe for target 'package/index' failed
make[2]: *** [package/index] Error 1
make[2]: Leaving directory '/root/lede-sdk-bcm53xx_gcc-5.4.0_musl-1.1.15_eabi.Linux-x86_64'
Makefile:55: recipe for target 'world' failed
make[1]: *** [world] Error 2
make[1]: Leaving directory '/root/lede-sdk-bcm53xx_gcc-5.4.0_musl-1.1.15_eabi.Linux-x86_64'
/root/lede-sdk-bcm53xx_gcc-5.4.0_musl-1.1.15_eabi.Linux-x86_64/include/toplevel.mk:190: recipe for target 'world' failed
make: *** [world] Error 2
root@VPS:~/lede-sdk-bcm53xx_gcc-5.4.0_musl-1.1.15_eabi.Linux-x86_64#

请问如何解决？谢谢！

**Comment by ywb94** [comment]
其实不用解决，IPK已经编译成功了，在bin目录

**Comment by GuangX3** [comment]
确实是编译成功了，安装时需要加上--force-depends，否则会提示内核不匹配。目前使用正常，非常感谢！
