### ISSUE TITLE
GFW-lede编译时出错，代码树编译

### ISSUE THREAD

**Issue by jack338c** [ywb94/openwrt-ssr#25]
Collected errors:
 * check_data_file_clashes: Package luci-app-shadowsocksR-GFW wants to install file /home/jack/source/build_dir/target-mips_24kc_musl-1.1.15/root-ar71xx/etc/dnsmasq.conf
	But that file is already provided by package  * dnsmasq-full
 * opkg_install_cmd: Cannot install package luci-app-shadowsocksR-GFW.
package/Makefile:60: recipe for target 'package/install' failed

**Comment by Copox** [comment]
你先把原先的dnsmasq.conf改名或者删掉 GFW版有自己的dnsmasq.conf

**Comment by jack338c** [comment]
@Copox 把/root-ar71xx/etc/dnsmasq.conf 这个文件删除，改名，都没有用，感谢指点

**Comment by Copox** [comment]
你目前给出的错误来判断，的确是“dnsmasq.conf”文件冲突

**Comment by jack338c** [comment]
2-76.6,

**Comment by Copox** [comment]
解决方案1 
作者说明文件提及
```
#刷新opkg列表
   opkg update

   #删除dnsmasq（GFW版本第一次安装需手动卸载dnsmasq，其他情况下不需要）
   opkg remove dnsmasq 

   #安装软件包
   opkg install /tmp/luci-app-shadowsocksR*_all.ipk 
```
方案2
安装IP路由版，手动配置gfw-list，曲线救国
方案3
这个是ss for openwrt作者的修改，有ip过滤黑名单(ignore-address)功能，达到ChinaDNS类似的效果
[https://github.com/aa65535/openwrt-dnsmasq](url)

**Comment by ywb94** [comment]
你是不是要把这个编译进固件？不要编译GFW版本，只编译原始版本 luci-app-shadowsocksR试试

**Comment by jack338c** [comment]
@ywb94 ，是的，那明白了，感谢！

**Comment by ywb94** [comment]
用新代码试试，加了预安装处理，发现/etc/dnsmasq.conf，会将其改名
