### ISSUE TITLE
在客户端页面点击添加按钮无效，总是跳回主客户端页面

### ISSUE THREAD

**Issue by SptrsCA** [ywb94/openwrt-ssr#26]
点击添加按钮，闪一下。就回来啦~
![qq 20170107090639](https://cloud.githubusercontent.com/assets/10737673/21737899/b0f3ca48-d4b8-11e6-8b2c-8577b445b0e8.png)

ar17xx
固件版本：(git-16.018.33482-3201903) / OpenWrt Chaos Calmer 15.05.1

**Comment by ywb94** [comment]
重启没有？

**Comment by SptrsCA** [comment]
已经重启。但是问题任然存在。

**Comment by ywb94** [comment]
按如下方法试试：
用winscp打开/usr/lib/lua/luci/model/cbi/shadowsocksr/client.lua文件
找到如下代码：
newconfig = luci.dispatcher.build_url("admin/services/shadowsocksr/client/%s")
function s.create(...)
	local sid = TypedSection.create(...)
	if sid then
		luci.http.redirect(newconfig % sid)
		return
	end
end

改为：
function s.create(self)
	local sid = TypedSection.create(self)
	if sid then
		luci.http.redirect(self.extedit  % sid)
		return
	end
end

然后保存文件，重启路由器

**Comment by ywb94** [comment]
用V1.1.8版本试试

**Comment by SptrsCA** [comment]
问题已修复√感谢。
之前没看到邮件推送。

**Comment by nimasi** [comment]
我用最新版的改了没效果，求助啊
