### ISSUE TITLE
GFW模式还是有些问题

### ISSUE THREAD

**Issue by daofeng2015** [ywb94/openwrt-ssr#27]
一会能打开谷歌.一会就不行了,切换为ip模式都能打开

**Comment by ywb94** [comment]
不科学啊。能不能反馈如下信息便于定位：
分别反馈能打开谷歌和不能打开谷歌时的如下信息：
1、在计算机上ping google
C:\Users\ywb>ping www.google.com
正在 Ping www.google.com [216.58.200.196] 具有 32 字节的数据:

2、登录openwrt，输入命令
ps |grep ss   
iptables -t nat -L 

在不能打开时openwrt上执行/etc/init.d/dnsmasq,之后看看能不能打开

**Comment by daofeng2015** [comment]
解决了,重启路由问题消失了,感谢作者！！！
