### ISSUE TITLE
按照作者给出的编译方法, 在进行./scripts/feeds install libpcre时出错

### ISSUE THREAD

**Issue by stelectronic** [ywb94/openwrt-ssr#29]
这一步如下:
ubuntu:~/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64$ ./scripts/feeds install libpcre
Ignoring feed 'base' - index missing
Ignoring feed 'luci' - index missing
Ignoring feed 'routing' - index missing
Ignoring feed 'telephony' - index missing
Ignoring feed 'management' - index missing
Installing package 'pcre'
WARNING: No feed for package 'libc' found, maybe it's already part of the standard packages?
WARNING: No feed for package 'libssp' found, maybe it's already part of the standard packages?
WARNING: No feed for package 'librt' found, maybe it's already part of the standard packages?
WARNING: No feed for package 'libpthread' found, maybe it's already part of the standard packages?
WARNING: No feed for package 'libc' found, maybe it's already part of the standard packages?
WARNING: No feed for package 'libssp' found, maybe it's already part of the standard packages?
WARNING: No feed for package 'librt' found, maybe it's already part of the standard packages?
WARNING: No feed for package 'libpthread' found, maybe it's already part of the standard packages?
WARNING: No feed for package 'libc' found, maybe it's already part of the standard packages?
WARNING: No feed for package 'libssp' found, maybe it's already part of the standard packages?
WARNING: No feed for package 'librt' found, maybe it's already part of the standard packages?
WARNING: No feed for package 'libpthread' found, maybe it's already part of the standard packages?
WARNING: No feed for package 'libstdcpp' found, maybe it's already part of the standard packages?

然后如果忽略这个继续下一步 make menuconfig就会:
make -s -C scripts/config all CC=mips-openwrt-linux-gcc: build failed. Please re-run make with -j1 V=s to see what's going on
/home/iamst/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/include/toplevel.mk:89: recipe for target 'scripts/config/mconf' failed
make: *** [scripts/config/mconf] Error 1

**Comment by stelectronic** [comment]
对了, 我的路由是ar71xx, op版本是Calmer 15.05.1, 有没有和我一样的直接发给我编译好的ipk⊙﹏⊙b

**Comment by ywb94** [comment]
release页面有ar71xx的ipk 
安装libpcre的提示信息没有问题，，make时加 -j1 V=s参数看实际的错误信息

**Comment by stelectronic** [comment]
@ywb94 

make menuconfig -j1 V=s

make[1]: Entering directory '/home/iamst/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/scripts/config'
/bin/sh: 1: mips-openwrt-linux-gcc: not found
<builtin>: recipe for target 'mconf.o' failed
make[1]: *** [mconf.o] Error 127
make[1]: Leaving directory '/home/iamst/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/scripts/config'
/home/iamst/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/include/toplevel.mk:89: recipe for target 'scripts/config/mconf' failed
make: *** [scripts/config/mconf] Error 2

**Comment by stelectronic** [comment]
@ywb94 我下载了release里面的文件, 文件名未注明对应openwrt版本号, 请问是15.05.1吗, 还是这个文件适合所有openwrt版本?

**Comment by ywb94** [comment]
15.05.1没问题

**Comment by stelectronic** [comment]
@ywb94 好吧, 我直接用你编译好的ipk了, 请问这个项目支持udp转发吗?我没看到udp相关的选项, 游戏里翻墙效果也并不好

**Comment by pzkj** [comment]
最新的sdk需要先执行命令 ./scripts/feeds update -a 而不是  ./scripts/feeds update packages  否则就会出现这个问题

**Comment by cloudchou** [comment]
最新的sdk需要先执行命令 ./scripts/feeds update -a 而不是 ./scripts/feeds update packages 否则就会出现这个问题

**Comment by maryshaw** [comment]
首先需保证make -j1 -V=s编译正常。这里遇到一个正则表达式的问题：
编辑./staging_dir/host/bin/automake-1.15，3938行给大括号添加转义'\'。
再次make menuconfig，如果存在1楼错误，注意检查scripts/config/mconf文件是否存在。
如果没有，修改./script/config/Makefile，Cflags后添加参数-fPIC
cd ./script/config/
make clean
make
cd ../../
make menuconfig
