### ISSUE TITLE
白名单方式(chinassr)下，teamviewer打开后连接老超时不成功，gfw模式没有这样问题

### ISSUE THREAD

**Issue by jack338c** [ywb94/openwrt-ssr#31]
如题，请有时间帮看看，感谢!

**Comment by ywb94** [comment]
信息太少。
首先teamviewer这个软件使用了哪些协议通讯？SSR只支持UDP、TCP代理，UDP代理需打开UDP中继
gfw没有问题，是不是把ssr全局代理停用也没有问题？除非你要连接的地址是GFW中的地址

**Comment by jack338c** [comment]
对，全局停运就正常

**Comment by jack338c** [comment]
另外，不翻墙，也正常

**Comment by ywb94** [comment]
将你teamviewr要连接的IP地址加入“额外被忽略IP”

**Comment by jack338c** [comment]
好的，我试试，多谢!
