### ISSUE TITLE
menuconfig 只有原版选项,并没有GFW

### ISSUE THREAD

**Issue by zaion520** [ywb94/openwrt-ssr#32]
menuconfig 只有原版选项,并没有GFW.makefile 看不懂- -各种宏到处飞,求大大指点一下

**Comment by ywb94** [comment]
先确认是否取的最新代码，打开makefile，最后一行应该是
$(eval $(call BuildPackage,luci-app-shadowsocksR-GFW))

**Comment by zaion520** [comment]
已经是最新,把最后ssr -client ssr-server 的 注释去掉 menuuconfig上 也显示出来,唯独gfw不行,我是添加到op源码编译的

**Comment by ywb94** [comment]
V1.1.8增加了coreutils依赖，需要在menuconfig中的Utilities中将coreutils选中，才会出现GFW选项

**Comment by zaion520** [comment]
GFW出现了 ,可是dnsmasq冲突uu,还是编译不过

**Comment by Ge0Lin** [comment]
集成编译时，同样出现与dnsmasq-full冲突
Collected errors:
 * check_data_file_clashes: Package luci-app-shadowsocksR-GFW wants to install file /home/ge/source/build_dir/target-arm_xscale_musl-1.1.15_eabi/root-kirkwood/etc/dnsmasq.conf
	But that file is already provided by package  * dnsmasq-full
 * opkg_install_cmd: Cannot install package luci-app-shadowsocksR-GFW.
package/Makefile:56: recipe for target 'package/install' failed
make[2]: *** [package/install] Error 255
make[2]: Leaving directory '/home/ge/source'
package/Makefile:125: recipe for target '/home/ge/source/staging_dir/target-arm_xscale_musl-1.1.15_eabi/stamp/.package_install' failed
make[1]: *** [/home/ge/source/staging_dir/target-arm_xscale_musl-1.1.15_eabi/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/ge/source'
/home/ge/source/include/toplevel.mk:194: recipe for target 'world' failed

**Comment by ywb94** [comment]
优化了makefile，减少dnsmasq的冲突，再用最新源码试试看行不行

**Comment by zaion520** [comment]
编译已通过
