### ISSUE TITLE
访问控制不生效

### ISSUE THREAD

**Issue by huaxianyan** [ywb94/openwrt-ssr#33]
安装了普通版，一切配置好之后看了下状态OK，里面的测试也OK，sock5代理试了下OK，就是访问控制一直不生效

我打算使用列表外/列表内的方法让某几个IP强制走代理，但是不论怎么排列组合，那个机器访问互联网均不走代理

路由器的访问控制是有效的，在测试里测试Google连通与否就能反应出来

**Comment by ywb94** [comment]
你的理解有误。LAN控制是控制内网哪些机器可以使用路由器的代理设置，哪些不能使用代理。
目前不能指定哪些机器强制走代理。

**Comment by huaxianyan** [comment]
那这个全局客户端是怎么生效的呢……我把访问控制关了也没发现路由器下的设备走代理

还是说SSR只是在路由器端运行一个客户端，但是没有system proxy只能用socks5的方式调用？

**Comment by ywb94** [comment]
访问控制关了，就是按配置规则全局透明代理，和sock5没关系。
路由器下的设备不走代理是不正常的。请检查配置和防火墙规则，有没有安装其他SS软件，路由器有没有重启

**Comment by huaxianyan** [comment]
原来有个spec版的SS，不过已经关闭了，查看进程确认没在运行。路由器已经重启过了，防火墙里好像没有奇怪的规则。

**Comment by ywb94** [comment]
如下信息反馈看看
iptables -t nat -L

**Comment by huaxianyan** [comment]
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
SS_SPEC_WAN_AC  tcp  --  anywhere             anywhere             ! match-set ss_spec_lan_ac src /* _SS_SPEC_RULE_ */
delegate_prerouting  all  --  anywhere             anywhere            

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
SS_SPEC_WAN_AC  tcp  --  anywhere             anywhere             /* _SS_SPEC_RULE_ */

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
delegate_postrouting  all  --  anywhere             anywhere            

Chain MINIUPNPD (1 references)
target     prot opt source               destination         
DNAT       udp  --  anywhere             anywhere             udp dpt:9308 to:192.168.7.164:9308

Chain SS_SPEC_WAN_AC (2 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere             match-set ss_spec_wan_ac dst
SS_SPEC_WAN_FW  all  --  anywhere             anywhere            

Chain SS_SPEC_WAN_FW (1 references)
target     prot opt source               destination         
REDIRECT   tcp  --  anywhere             anywhere             redir ports 37777

Chain delegate_postrouting (1 references)
target     prot opt source               destination         
postrouting_rule  all  --  anywhere             anywhere             /* user chain for postrouting */
zone_lan_postrouting  all  --  anywhere             anywhere            
zone_wan_postrouting  all  --  anywhere             anywhere            

Chain delegate_prerouting (1 references)
target     prot opt source               destination         
prerouting_rule  all  --  anywhere             anywhere             /* user chain for prerouting */
zone_lan_prerouting  all  --  anywhere             anywhere            
zone_wan_prerouting  all  --  anywhere             anywhere            

Chain postrouting_lan_rule (1 references)
target     prot opt source               destination         

Chain postrouting_rule (1 references)
target     prot opt source               destination         

Chain postrouting_wan_rule (1 references)
target     prot opt source               destination         

Chain prerouting_lan_rule (1 references)
target     prot opt source               destination         

Chain prerouting_rule (1 references)
target     prot opt source               destination         

Chain prerouting_wan_rule (1 references)
target     prot opt source               destination         

Chain zone_lan_postrouting (1 references)
target     prot opt source               destination         
postrouting_lan_rule  all  --  anywhere             anywhere             /* user chain for postrouting */

Chain zone_lan_prerouting (1 references)
target     prot opt source               destination         
prerouting_lan_rule  all  --  anywhere             anywhere             /* user chain for prerouting */

Chain zone_wan_postrouting (1 references)
target     prot opt source               destination         
postrouting_wan_rule  all  --  anywhere             anywhere             /* user chain for postrouting */
MASQUERADE  all  --  anywhere             anywhere            

Chain zone_wan_prerouting (1 references)
target     prot opt source               destination         
MINIUPNPD  all  --  anywhere             anywhere            
prerouting_wan_rule  all  --  anywhere             anywhere             /* user chain for prerouting */

**Comment by ywb94** [comment]
先把LAN访问控制去掉。
1、在计算机上ping google，看能不能解析正确IP
C:\>ping www.google.com
正在 Ping www.google.com [216.58.200.196] 具有 32 字节的数据:
2、登录openwrt，输入命令
ps |grep ss
查看信息

3、在不能打开时清dns缓存试试
openwrt上执行/etc/init.d/dnsmasq restart
计算机上执行ipconfig/flushdns,之后看看能不能打开

**Comment by huaxianyan** [comment]
1.访问控制路由器那里是正常代理，内网访问控制是停用
ping www.google.com解析出的IP是相同的，但是全部超时
2.得到如下信息
 8807 root      3716 S    /usr/bin/ssr-redir -c /var/etc/shadowsocksr.json -u -f /var/
 8815 root      3264 S    /usr/bin/ssr-tunnel -c /var/etc/shadowsocksr.json -u -l 5300
 8855 root      4320 S    /usr/bin/ssr-local -c /var/etc/shadowsocksr_s.json -u -l 377
 8862 root      1372 S    {ssr-monitor} /bin/sh /usr/bin/ssr-monitor 0 1 0 1 0 1 0
 8976 root      1356 S    grep ss
3.全部清过，没有什么变化

**Comment by ywb94** [comment]
ping www.google.com肯定是超时的，要看它的IP是什么，判断DNS是否正常
如不正常，看dnsmasq配置或者服务器端是否启用了UDP转发

**Comment by huaxianyan** [comment]
ping出的IP是216.58.200.196，是正常的
dnsmasq好像是默认配置，没有开DNS转发之类的，因为没有ChinaDNS之类的程序
服务端指的是路由器上的SSR服务端还是SS的服务端？前者没开启后者的确是有UDP转发

**Comment by ywb94** [comment]
你用的是SS服务器？协议是不是设置成origin，混淆设成plain？

**Comment by huaxianyan** [comment]
服务器端是SSR，说实话就是因为想开混淆才找openWRT端的SSR，否则就直接还是用SS-spec了，协议是auth_aes128_sha1,tls1.2_ticket-auth
理论上socks5代理能用应该不是SS本身的问题。
至于IP路由模式和GFW模式是不是要安装GFWlist版才能选择？我安装的是基础版，如果是的话晚上我回去卸载了重新安装一下

**Comment by ywb94** [comment]
使用基础版本，dns解析地址应该是错的才对，我看你自己开了dns隧道，你自己是怎么对dns处理的？
`8815 root      3264 S    /usr/bin/ssr-tunnel -c /var/etc/shadowsocksr.json -u -l 5300`

**Comment by huaxianyan** [comment]
只开了一个pdnsd，其他没有开

**Comment by ywb94** [comment]
先关了试试

**Comment by huaxianyan** [comment]
好，晚上回去我关了试试。另外我刚才仔细读了一下说明，发现有一句就是socks5的端口不能和SS配置里的本地端口相同，我在想是不是socks5开启了占用了这个端口导致ss配置里本地端口失效，然后透明代理无效？

**Comment by ywb94** [comment]
设置一样肯定是错误的

**Comment by huaxianyan** [comment]
远程了一下家里的机器，本地端口和socks5端口设置不一样，pdnsd已经关掉，不过依旧没效。
我连socks5和dns隧道也关闭了，状态里3个检查都OK，不过看了看电脑的IP，依旧是本地电信的IP

**Comment by ywb94** [comment]
google一般情况下是ping不通的，因为ss/ssr只是针对tcp、udp代理，ping是icmp报文，ping的目的主要看dns解析是否正确

**Comment by huaxianyan** [comment]
汇报一下，1.1.9 GFW版本，IP路由模式状态里测试都OK,PING返回的IP也对，DNS没有问题
GFWLIST模式，测试里GOOGLE测试不通过，PING不出IP
然后任何模式下都不能访问youtube，访问控制停用，pdnsd在安装了gfw版本后就关了

**Comment by huaxianyan** [comment]
感觉救不了了，只能归结为不是官方版的openWRT，回头刷个最新的官方OP CC好了

不过明月版省了不少事就是了……

**Comment by huaxianyan** [comment]
刷了官方原版的OP CC之后没问题了，看来明月版不知道动了什么我不懂的东西导致失败。感谢作者一直帮忙到现在，这条可以closed了
