### ISSUE TITLE
安装成功，但无法翻墙

### ISSUE THREAD

**Issue by GuangX3** [ywb94/openwrt-ssr#35]
Google Connectivity显示连接错误

在一级路由上部署，版本是1.1.9。查看日志发现：

Thu Jan 12 18:00:56 2017 user.err ssr-rules[1374]: Start failed!
Thu Jan 12 18:00:56 2017 kern.info /usr/bin/ssr-redir[1449]: initializing ciphers... chacha20-ietf
Thu Jan 12 18:00:56 2017 kern.info /usr/bin/ssr-redir[1449]: tcp port reuse enabled
Thu Jan 12 18:00:56 2017 kern.info /usr/bin/ssr-redir[1449]: listening at 0.0.0.0:1234
Thu Jan 12 18:00:56 2017 kern.info /usr/bin/ssr-redir[1449]: running from root user

系统是LEDE

**Comment by ywb94** [comment]
反馈信息：
iptables -t nat -L

**Comment by GuangX3** [comment]
你好，

信息如下：

Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
prerouting_rule  all  --  anywhere             anywhere             /* !fw3: user chain for prerouting */
zone_lan_prerouting  all  --  anywhere             anywhere             /* !fw3 */
zone_wan_prerouting  all  --  anywhere             anywhere             /* !fw3 */
zone_wan_prerouting  all  --  anywhere             anywhere             /* !fw3 */

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
postrouting_rule  all  --  anywhere             anywhere             /* !fw3: user chain for postrouting */
zone_lan_postrouting  all  --  anywhere             anywhere             /* !fw3 */
zone_wan_postrouting  all  --  anywhere             anywhere             /* !fw3 */
zone_wan_postrouting  all  --  anywhere             anywhere             /* !fw3 */

Chain postrouting_lan_rule (1 references)
target     prot opt source               destination

Chain postrouting_rule (1 references)
target     prot opt source               destination

Chain postrouting_wan_rule (1 references)
target     prot opt source               destination

Chain prerouting_lan_rule (1 references)
target     prot opt source               destination

Chain prerouting_rule (1 references)
target     prot opt source               destination

Chain prerouting_wan_rule (1 references)
target     prot opt source               destination

Chain zone_lan_postrouting (1 references)
target     prot opt source               destination
postrouting_lan_rule  all  --  anywhere             anywhere             /* !fw3: user chain for postrouting */

Chain zone_lan_prerouting (1 references)
target     prot opt source               destination
prerouting_lan_rule  all  --  anywhere             anywhere             /* !fw3: user chain for prerouting */

Chain zone_wan_postrouting (2 references)
target     prot opt source               destination
postrouting_wan_rule  all  --  anywhere             anywhere             /* !fw3: user chain for postrouting */
MASQUERADE  all  --  anywhere             anywhere             /* !fw3 */

Chain zone_wan_prerouting (2 references)
target     prot opt source               destination
prerouting_wan_rule  all  --  anywhere             anywhere             /* !fw3: user chain for prerouting */

**Comment by ywb94** [comment]
防火墙规则没起来，检查你的服务器配置是否正确

**Comment by GuangX3** [comment]
你好，刚刚不好意思，因为之前启动不成功，所以客户端没开

Thu Jan 12 21:19:19 2017 user.err ssr-rules[2444]: Start failed!
Thu Jan 12 21:19:19 2017 kern.info /usr/bin/ssr-redir[2519]: initializing ciphers... chacha20-ietf
Thu Jan 12 21:19:19 2017 kern.info /usr/bin/ssr-redir[2519]: tcp port reuse enabled
Thu Jan 12 21:19:19 2017 kern.info /usr/bin/ssr-redir[2519]: UDP relay enabled
Thu Jan 12 21:19:19 2017 kern.info /usr/bin/ssr-redir[2519]: udp port reuse enabled
Thu Jan 12 21:19:19 2017 kern.info /usr/bin/ssr-redir[2519]: listening at 0.0.0.0:1234
Thu Jan 12 21:19:19 2017 kern.info /usr/bin/ssr-redir[2519]: running from root user
Thu Jan 12 21:19:19 2017 kern.info /usr/bin/ssr-tunnel[2529]: initializing ciphers... chacha20-ietf
Thu Jan 12 21:19:19 2017 kern.info /usr/bin/ssr-tunnel[2529]: tcp port reuse enabled
Thu Jan 12 21:19:19 2017 kern.info /usr/bin/ssr-tunnel[2529]: UDP relay enabled
Thu Jan 12 21:19:19 2017 kern.info /usr/bin/ssr-tunnel[2529]: udp port reuse enabled
Thu Jan 12 21:19:19 2017 kern.info /usr/bin/ssr-tunnel[2529]: listening at 0.0.0.0:5300
Thu Jan 12 21:19:19 2017 kern.info /usr/bin/ssr-tunnel[2529]: running from root user




Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
prerouting_rule  all  --  anywhere             anywhere             /* !fw3: user chain for prerouting */
zone_lan_prerouting  all  --  anywhere             anywhere             /* !fw3 */
zone_wan_prerouting  all  --  anywhere             anywhere             /* !fw3 */
zone_wan_prerouting  all  --  anywhere             anywhere             /* !fw3 */

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
postrouting_rule  all  --  anywhere             anywhere             /* !fw3: user chain for postrouting */
zone_lan_postrouting  all  --  anywhere             anywhere             /* !fw3 */
zone_wan_postrouting  all  --  anywhere             anywhere             /* !fw3 */
zone_wan_postrouting  all  --  anywhere             anywhere             /* !fw3 */

Chain SS_SPEC_WAN_FW (0 references)
target     prot opt source               destination
REDIRECT   tcp  --  anywhere             anywhere             redir ports 1234

Chain postrouting_lan_rule (1 references)
target     prot opt source               destination

Chain postrouting_rule (1 references)
target     prot opt source               destination

Chain postrouting_wan_rule (1 references)
target     prot opt source               destination

Chain prerouting_lan_rule (1 references)
target     prot opt source               destination

Chain prerouting_rule (1 references)
target     prot opt source               destination

Chain prerouting_wan_rule (1 references)
target     prot opt source               destination

Chain zone_lan_postrouting (1 references)
target     prot opt source               destination
postrouting_lan_rule  all  --  anywhere             anywhere             /* !fw3: user chain for postrouting */

Chain zone_lan_prerouting (1 references)
target     prot opt source               destination
prerouting_lan_rule  all  --  anywhere             anywhere             /* !fw3: user chain for prerouting */

Chain zone_wan_postrouting (2 references)
target     prot opt source               destination
postrouting_wan_rule  all  --  anywhere             anywhere             /* !fw3: user chain for postrouting */
MASQUERADE  all  --  anywhere             anywhere             /* !fw3 */

Chain zone_wan_prerouting (2 references)
target     prot opt source               destination
prerouting_wan_rule  all  --  anywhere             anywhere             /* !fw3: user chain for prerouting */

服务器的信息确认是没填错的，在另外一台机器上，相同的配置，没有问题

**Comment by ywb94** [comment]
防火墙规则建立失败。
输入以下命令，看有什么信息
ipset -v  
ipset create ss_spec_wan_ac hash:net
ipset -X ss_spec_wan_ac 
iptables -N SS_SPEC_WAN_AC
iptables -X SS_SPEC_WAN_AC

**Comment by GuangX3** [comment]
你好，输出如下:

root@R6300V2:~# ipset -v
ipset v6.30, protocol version: 6
root@R6300V2:~# ipset create ss_spec_wan_ac hash:net
ipset v6.30: Cannot open session to kernel.
root@R6300V2:~# ipset -X ss_spec_wan_ac
ipset v6.30: Cannot open session to kernel.
root@R6300V2:~# iptables -N SS_SPEC_WAN_AC
root@R6300V2:~# iptables -X SS_SPEC_WAN_AC
root@R6300V2:~#

**Comment by ywb94** [comment]
重启路由器

**Comment by GuangX3** [comment]
重启还是不行，输入ipset create ss_spec_wan_ac hash:net，还是提示ipset Cannot open session to kernel

可能是因为我安装的LEDE是snapshot的原因。另一台安装的是恩山上的固件，是4.4.40的内核，那台就没有问题

我google一下
