### ISSUE TITLE
建议在gfwlist加入Google HK和Google SG。

### ISSUE THREAD

**Issue by daniuer** [ywb94/openwrt-ssr#36]
今天在用新加坡和阿里云节点的时候，发现Android的Google搜索会跳转到Google HK，然后页面就僵在那里。猜测gfwlist列表里没有这两个的域名。手动添加并/etc/init.d/dnsmasq restart后手机上可以正常搜索了。
如果是日本和美国的域名不会有这个问题，电脑版默认打开的是googl.com也不会有这个问题。
我自己添加后，下次更新新版或者手动更新【GFW列表】数据库文件会被覆盖。希望作者大大能加入这两个域名，让我们一劳永逸，谢谢。
server=/.google.com.hk/127.0.0.1#5353
ipset=/.google.com.hk/gfwlist
server=/.google.com.sg/127.0.0.1#5353
ipset=/.google.com.sg/gfwlist

**Comment by ywb94** [comment]
自定义GFW规则的方法：
在目录/etc/dnsmasq.ssr下创建一个文件，名称任取，比如myrules.conf，按要求输入你需要添加的网址
比如要添加google.com.hk，需输入两行：
server=/.google.com.hk/127.0.0.1#5353
ipset=/.google.com.hk/gfwlist

**Comment by daniuer** [comment]
这个办法好，又灵活方便，谢谢指教。

**Comment by daniuer** [comment]
补问监控日志和自动切换日志在哪里查看？

**Comment by ywb94** [comment]
Openwrt的“系统日志”

**Comment by daniuer** [comment]
看到了，谢谢。
