### ISSUE TITLE
能开机自动更新数据库码？

### ISSUE THREAD

**Issue by daofeng2015** [ywb94/openwrt-ssr#40]
每次手动点好麻烦，或者定时任务

**Comment by ywb94** [comment]
不建议频繁更新数据库，几个月更新一次足以，没问题也不用更新

**Comment by daofeng2015** [comment]
但是你那个广告过滤完全没效果啊。。。。能换个过滤规则吗？

**Comment by ywb94** [comment]
有没有好的列表推荐

**Comment by daofeng2015** [comment]
https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/ABP-FX.txt

**Comment by daofeng2015** [comment]
https://gist.githubusercontent.com/myfreeer/12108f109de00d9d667bd686b11eeaa1/raw/urule.txt

**Comment by ywb94** [comment]
ok，考虑整合
