### ISSUE TITLE
Build R7800 fail

### ISSUE THREAD

**Issue by ykglove** [ywb94/openwrt-ssr#41]
Signing package index...
Cannot open file '/home/test/lede-project/lede-sdk-ipq806x_gcc-5.4.0_musl-1.1.16_eabi.Linux-x86_64/key-build' for reading
Cannot open file '/home/test/lede-project/lede-sdk-ipq806x_gcc-5.4.0_musl-1.1.16_eabi.Linux-x86_64/key-build' for reading
Cannot open file '/home/test/lede-project/lede-sdk-ipq806x_gcc-5.4.0_musl-1.1.16_eabi.Linux-x86_64/key-build' for reading
Cannot open file '/home/test/lede-project/lede-sdk-ipq806x_gcc-5.4.0_musl-1.1.16_eabi.Linux-x86_64/key-build' for reading
Cannot open file '/home/test/lede-project/lede-sdk-ipq806x_gcc-5.4.0_musl-1.1.16_eabi.Linux-x86_64/key-build' for reading
Cannot open file '/home/test/lede-project/lede-sdk-ipq806x_gcc-5.4.0_musl-1.1.16_eabi.Linux-x86_64/key-build' for reading
Cannot open file '/home/test/lede-project/lede-sdk-ipq806x_gcc-5.4.0_musl-1.1.16_eabi.Linux-x86_64/key-build' for reading
package/Makefile:78: recipe for target 'package/index' failed
make[2]: *** [package/index] Error 1
make[2]: Leaving directory '/home/test/lede-project/lede-sdk-ipq806x_gcc-5.4.0_musl-1.1.16_eabi.Linux-x86_64'
Makefile:55: recipe for target 'world' failed
make[1]: *** [world] Error 2
make[1]: Leaving directory '/home/test/lede-project/lede-sdk-ipq806x_gcc-5.4.0_musl-1.1.16_eabi.Linux-x86_64'
/home/test/lede-project/lede-sdk-ipq806x_gcc-5.4.0_musl-1.1.16_eabi.Linux-x86_64/include/toplevel.mk:190: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by ywb94** [comment]
没有关系，未签名错误，ipk已经在bin目录
