### ISSUE TITLE
请问PDNSD端口设置在哪里，LUCI界面还是PDNSD.conf

### ISSUE THREAD

**Issue by jack338c** [ywb94/openwrt-ssr#42]
请问PDNSD端口设置在哪里，LUCI界面还是PDNSD.conf

**Comment by ywb94** [comment]
支持pdnsd的源码已更新，但还未发布。用最新源码编译的端口设置还是在/etc/pdnsd.conf

**Comment by jack338c** [comment]
好的，现在只用你的包，多谢了

**Comment by ywb94** [comment]
pdnsd需另外自行安装、配置、启动和停止，现在和pdnsd是弱相关的关系，在考虑是否要捆绑控制

**Comment by jack338c** [comment]
https://github.com/sxx1314/luci-app-shadowsocksR。可以参考下这个

**Comment by ywb94** [comment]
ok，已增加对pdnsd控制，自行安装pdnsd后，由luci界面控制pdnsd，在界面上设置dns(tcp)服务器和端口

**Comment by jack338c** [comment]
好，太棒了，正在测试中！

**Comment by jack338c** [comment]
目前没发现问题，是我用过最好的FQ方案，几乎完美
这里请教下：
IPROUTER和GFW MODE 下都用下面同一个PDNSD配置文件吗，还是根据切换后不一样的配置？

global {
	perm_cache=10240;
	cache_dir="/var/pdnsd";
	pid_file = /var/run/pdnsd.pid;
	run_as="nobody";
	server_ip = 127.0.0.1;
	server_port = 5353;
	status_ctl = on;
	query_method = tcp_only;
	min_ttl=1h;
	max_ttl=1w;
	timeout=10;
	neg_domain_pol=on;
	proc_limit=2;
	procq_limit=8;
}
server {
	label= "ssr-usrdns";
	ip = 8.8.4.4;
	port = 53;
	timeout=6;
	uptest=none;
	interval=10m;
	purge_cache=off;
}
server {
	label= "ssr-pdnsd";
	ip = 208.67.222.222, 208.67.220.220;
	port = 5353;
	timeout=6;
	uptest=none;
	interval=10m;
	purge_cache=off;
}

**Comment by ywb94** [comment]
1将8.8.4.4加入强制走代理的IP
2 IP路由和gfw列表模式下dns处理方式一样，配置文件也相同

**Comment by jack338c** [comment]
好，这就去试试，多谢!

**Comment by jack338c** [comment]
经测试，目前这是我用过的最理想FQ方案，几乎完美，感谢ywb94辛勤付出！
