### ISSUE TITLE
Camellia加密方式无法使用

### ISSUE THREAD

**Issue by GuangX3** [ywb94/openwrt-ssr#43]
直接安装release里面的ipk文件，使用aes加密连接正常，换成camellia报错

Wed Jan 18 20:15:09 2017 kern.info /usr/bin/ssr-tunnel[7103]: initializing ciphers... camellia-192-cfb
Wed Jan 18 20:15:09 2017 kern.err /usr/bin/ssr-tunnel[7103]: Cipher camellia-192-cfb not found in crypto library

**Comment by ywb94** [comment]
换个高版本的libopenssl试试

**Comment by ywb94** [comment]
看cc 15.05.1的openssl的makefile
https://github.com/openwrt/openwrt/blob/v15.05.1/package/libs/openssl/Makefile

里面将camellia加密给去掉了
OPENSSL_NO_CIPHERS:= no-idea no-md2 no-mdc2 no-rc5 no-sha0 no-camellia no-krb5
如果安装官方的IPK，将没有camellia加密和idea-cfb加密，如果要加上，需重新编译libopenssl，卸载官方的，安装自己编译的

**Comment by GuangX3** [comment]
Hi，

明白了，感谢解答，可以关掉这个issue了。
