### ISSUE TITLE
每次路由重启，必须手动启动，才可以用

### ISSUE THREAD

**Issue by jevonryan** [ywb94/openwrt-ssr#44]
重启路由必须在web页面点保存并应用才能正常使用
或者在ssh端/etc/init.d/shadowsocksr strat 操作
在/etc/rc.local添加etc/init.d/shadowsocksr strat  也不行
这是为什么呢，版本是自己编译的。

**Comment by ywb94** [comment]
看看openwrt的系统日志

**Comment by jevonryan** [comment]
我试过在ip路由模式下路由开机后shadowsocksr是能正常使用的，在列表模式下就必须手动启动shadowsocksr才能正常使用，这两种shadowsocksr模式启动，openwrt的开机系统日志里只有dnsmasq的启动信息，openwrt版本15.05.1

**Comment by jevonryan** [comment]
刚刚重新编译的shadowsocksr版本也是同样的问题，问题只出现在“列表模式”，IP路由模式正常。
openwrt开机后的进程
 931 root      1152 S    /usr/sbin/dropbear -F -P /var/run/dropbear.1.pid -p 22 -K 300
  968 root      1596 S    /usr/sbin/uhttpd -f -h /www -r OpenWrt -x /cgi-bin -u /ubus -t 60 -T 30 -k 20 -A 1 -n 3 -N 100 -
 1131 root      3200 S    /usr/bin/ssr-redir -c /var/etc/shadowsocksr.json -f /var/run/ssr-retcp.pid
 1169 root      3224 S    /usr/bin/ssr-tunnel -c /var/etc/shadowsocksr.json -b 0.0.0.0 -u -l 5353 -L 8.8.4.4:53 -f /var/ru
 1180 root      1372 S    {ssr-monitor} /bin/sh /usr/bin/ssr-monitor 0 1 0 0 0 0 1 0
 1242 root       800 S    odhcp6c -s /lib/netifd/dhcpv6.script -P0 -t120 eth0.2
 1243 root      1360 S    udhcpc -p /var/run/udhcpc-eth0.2.pid -s /lib/netifd/dhcp.script -f -t 0 -i eth0.2 -C
 1259 root      1364 S    /usr/sbin/ntpd -n -S /usr/sbin/ntpd-hotplug -p 0.openwrt.pool.ntp.org -p 1.openwrt.pool.ntp.org
 1297 nobody    2944 S    /usr/sbin/dnsmasq -C /var/etc/dnsmasq.conf -k -x /var/run/dnsmasq/dnsmasq.pid
 1561 root      1352 S    sleep 30
 1562 root      1216 R    /usr/sbin/dropbear -F -P /var/run/dropbear.1.pid -p 22 -K 300
 1563 root      1364 S    -ash

openwrt开机后重启shadowsocksr后的进程（重启方法：ssh  /etc/init.d/shadowsocksr restart）
 931 root      1152 S    /usr/sbin/dropbear -F -P /var/run/dropbear.1.pid -p 22 -K 300
  968 root      1596 S    /usr/sbin/uhttpd -f -h /www -r OpenWrt -x /cgi-bin -u /ubus -t 60 -T 30 -k 20 -A 1 -n 3 -N 100 -
 1242 root       800 S    odhcp6c -s /lib/netifd/dhcpv6.script -P0 -t120 eth0.2
 1243 root      1360 S    udhcpc -p /var/run/udhcpc-eth0.2.pid -s /lib/netifd/dhcp.script -f -t 0 -i eth0.2 -C
 1259 root      1364 S    /usr/sbin/ntpd -n -S /usr/sbin/ntpd-hotplug -p 0.openwrt.pool.ntp.org -p 1.openwrt.pool.ntp.org
 1297 nobody    2944 S    /usr/sbin/dnsmasq -C /var/etc/dnsmasq.conf -k -x /var/run/dnsmasq/dnsmasq.pid
 1562 root      1216 R    /usr/sbin/dropbear -F -P /var/run/dropbear.1.pid -p 22 -K 300
 1563 root      1368 S    -ash
 1648 root      1352 S    sleep 30
 1815 root      3232 S    /usr/bin/ssr-redir -c /var/etc/shadowsocksr.json -f /var/run/ssr-retcp.pid
 1825 root      3208 S    /usr/bin/ssr-tunnel -c /var/etc/shadowsocksr.json -b 0.0.0.0 -u -l 5353 -L 8.8.4.4:53 -f /var/ru
 1834 root      1372 S    {ssr-monitor} /bin/sh /usr/bin/ssr-monitor 0 1 0 0 0 0 1 0
 1852 root      1352 S    sleep 30

**Comment by ywb94** [comment]
看进程没什么问题，你重启后输入
iptables -t nat -L
看输出什么信息，然后ping google看返回的IP地址是多少

**Comment by jevonryan** [comment]
路由重启后iptables -t nat -L及ping
root@OpenWrt:~# iptables -t nat -L
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
SS_SPEC_WAN_AC  tcp  --  anywhere             anywhere             /* _SS_SPEC_RULE_ */
SS_SPEC_WAN_AC  tcp  --  anywhere             anywhere             /* _SS_SPEC_RULE_ */
SS_SPEC_WAN_AC  tcp  --  anywhere             anywhere             /* _SS_SPEC_RULE_ */
SS_SPEC_WAN_AC  tcp  --  anywhere             anywhere             /* _SS_SPEC_RULE_ */
delegate_prerouting  all  --  anywhere             anywhere            

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
SS_SPEC_WAN_AC  tcp  --  anywhere             anywhere             /* _SS_SPEC_RULE_ */
SS_SPEC_WAN_AC  tcp  --  anywhere             anywhere             /* _SS_SPEC_RULE_ */
SS_SPEC_WAN_AC  tcp  --  anywhere             anywhere             /* _SS_SPEC_RULE_ */
SS_SPEC_WAN_AC  tcp  --  anywhere             anywhere             /* _SS_SPEC_RULE_ */

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
delegate_postrouting  all  --  anywhere             anywhere            

Chain SS_SPEC_WAN_AC (8 references)
target     prot opt source               destination         
SS_SPEC_WAN_FW  all  --  anywhere             anywhere             match-set gfwlist dst

Chain SS_SPEC_WAN_FW (1 references)
target     prot opt source               destination         
REDIRECT   tcp  --  anywhere             anywhere             redir ports 1080

Chain delegate_postrouting (1 references)
target     prot opt source               destination         
postrouting_rule  all  --  anywhere             anywhere             /* user chain for postrouting */
zone_lan_postrouting  all  --  anywhere             anywhere            
zone_wan_postrouting  all  --  anywhere             anywhere            

Chain delegate_prerouting (1 references)
target     prot opt source               destination         
prerouting_rule  all  --  anywhere             anywhere             /* user chain for prerouting */
zone_lan_prerouting  all  --  anywhere             anywhere            
zone_wan_prerouting  all  --  anywhere             anywhere            

Chain postrouting_lan_rule (1 references)
target     prot opt source               destination         

Chain postrouting_rule (1 references)
target     prot opt source               destination         

Chain postrouting_wan_rule (1 references)
target     prot opt source               destination         

Chain prerouting_lan_rule (1 references)
target     prot opt source               destination         

Chain prerouting_rule (1 references)
target     prot opt source               destination         

Chain prerouting_wan_rule (1 references)
target     prot opt source               destination         

Chain zone_lan_postrouting (1 references)
target     prot opt source               destination         
postrouting_lan_rule  all  --  anywhere             anywhere             /* user chain for postrouting */

Chain zone_lan_prerouting (1 references)
target     prot opt source               destination         
prerouting_lan_rule  all  --  anywhere             anywhere             /* user chain for prerouting */

Chain zone_wan_postrouting (1 references)
target     prot opt source               destination         
postrouting_wan_rule  all  --  anywhere             anywhere             /* user chain for postrouting */
MASQUERADE  all  --  anywhere             anywhere            

Chain zone_wan_prerouting (1 references)
target     prot opt source               destination         
prerouting_wan_rule  all  --  anywhere             anywhere             /* user chain for prerouting */
root@OpenWrt:~# ping www.google.com
PING www.google.com (216.58.221.228): 56 data bytes

**Comment by ywb94** [comment]
看不出问题，除了防火墙规则多了几条重复的，都很正常，dns也能正常解析，应该没有问题。
我这边不能重新你的问题，不知你对系统有没有做其他的改动？

**Comment by ywb94** [comment]
重启后执行/etc/init.d/firewall restart 看看能不能正常

**Comment by jevonryan** [comment]
openwrt15.05.1 是用的openwrt官方编译的版本，重启后执行/etc/init.d/firewall restart 问题依旧，路由器为网件3700v4版本。我不明白的是，为什么重启后手动执行/etc/init.d/shadowsocksr restart 就能正常访问Google等，IP路由模式，没有问题。

**Comment by ywb94** [comment]
重启后ping google，然后ipset list gfwlist看输出信息

**Comment by jevonryan** [comment]
root@OpenWrt:~# dig www.google.com @127.0.0.1 -p 53

; <<>> DiG 9.9.8-P3 <<>> www.google.com @127.0.0.1 -p 53
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 29694
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1280
;; QUESTION SECTION:
;www.google.com.			IN	A

;; ANSWER SECTION:
www.google.com.		173	IN	A	216.58.221.228

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Sat Jan 21 04:51:12 GMT 2017
;; MSG SIZE  rcvd: 59

看dns解析应该是正常的

ipset list gfwlist输出信息
root@OpenWrt:~# ipset list gfwlist
Name: gfwlist
Type: hash:ip
Revision: 4
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 8424
References: 1
Members:
104.237.191.1
192.30.253.124
192.30.253.113
192.30.253.125
216.239.32.116
216.58.221.238
192.30.253.112
74.125.141.94
172.217.24.35
216.58.200.46
216.58.221.228

**Comment by ywb94** [comment]
你没开sock5吧，我看你全局代理的本地端口改成了1080，和sock5缺省端口冲突

**Comment by jevonryan** [comment]
sock5我没有开的，我晚上回去吧系统退回15.05试试

**Comment by jevonryan** [comment]
openwrt 15.05 也是一样的问题，本地端口就算该别的端口也是一样的问题。

**Comment by ywb94** [comment]
看不出问题来，所有信息都正常，复现不了，也没有其它人反馈这个问题。
你的配置和组网有没有比较特别的？

**Comment by jevonryan** [comment]
没有啊，openwrt系统里就只装shadowsocksr，就用路由模式撑着吧。谢谢你的解答

**Comment by jevonryan** [comment]
从这几天使用来看，我的觉得，还是ip路由模式比较稳定，列表模式，我使用一直有问题。我个人觉得pdnsd的效率并不是很高，dns服务器我更喜欢用dnscrypt。
