### ISSUE TITLE
openwrt端工作不稳定

### ISSUE THREAD

**Issue by 1001knight** [ywb94/openwrt-ssr#45]
SSR for OpenWRT V1.2.0刷到路由器wndr4300上，vps配置：443；chacha20；auth_aes128_md5；tls1.2_ticket_auth
使用win7 64客户端测试YouTube速度12000以上，但路由器不正常，auth_aes128_md5，tls1.2_ticket_auth只有1000多k，换成plain混淆速度达到12000，和pc客户端速度一致。但更换视频后速度会恢复1000k以下

**Comment by ywb94** [comment]
是不是路由器性能限制，我一般用rc4-md5加密

**Comment by ywb94** [comment]
是不是路由器性能限制，我一般用rc4-md5加密

**Comment by GuangX3** [comment]
我用的是WNDR3800CH，性能应该和4300差不多， 用加密方式aes-192-cfb， auth_aes128_md5，tls1.2_ticket_auth相同，基本稳定在15000，感觉一楼会不会是线路的原因？

**Comment by 1001knight** [comment]
三楼正解，是线路原因。每天速度都不一样。快时18k+，慢时80k。上哪说理去？
