### ISSUE TITLE
请问，Server版支持udp不？

### ISSUE THREAD

**Issue by Copox** [ywb94/openwrt-ssr#46]
近日在lede部署server版成功，经测试TCP通道OK，UDP不通，假若不支持请作者考虑添加该功能，万分感谢

**Comment by ywb94** [comment]
你的udp应用场景是什么？

**Comment by Copox** [comment]
udp转发，中继，大多数用于游戏， 
网页浏览效率很高，内存cpu占用也很小，基本跑满，遗憾的是用电脑客户端如sscap测试UDP不通，也不知道如何设置跟检测

**Comment by Copox** [comment]
那server版本身支持UDP不？还是我配置错误，导致udp不通

**Comment by ywb94** [comment]
应该支持，没测试过，没有应用场景，手机上一般也不用udp

**Comment by Copox** [comment]
TCP跟UDP都没问题，感谢作者回答
