### ISSUE TITLE
添加kcptun脚本？

### ISSUE THREAD

**Issue by nu1ee** [ywb94/openwrt-ssr#48]
`.:
总用量 16
drwxrwxr-x  3 nulee nulee 4096 1月  25 00:37 .
drwxrwxr-x 32 nulee nulee 4096 1月  25 00:13 ..
drwxrwxr-x  8 nulee nulee 4096 1月  25 00:30 files
-rw-rw-r--  1 nulee nulee 1544 1月  25 00:37 Makefile

./files:
总用量 32
drwxrwxr-x 8 nulee nulee 4096 1月  25 00:30 .
drwxrwxr-x 3 nulee nulee 4096 1月  25 00:37 ..
drwxrwxrwx 2 nulee nulee 4096 1月  25 00:31 7620n
drwxrwxrwx 2 nulee nulee 4096 1月  25 00:31 ar71xx
drwxrwxr-x 2 nulee nulee 4096 1月  25 00:32 arm
drwxrwxrwx 4 nulee nulee 4096 1月   4 10:12 etc
drwxrwxrwx 2 nulee nulee 4096 1月  25 00:28 x86
drwxrwxrwx 2 nulee nulee 4096 1月  25 00:27 x86_64

./files/7620n:
总用量 3328
drwxrwxrwx 2 nulee nulee    4096 1月  25 00:31 .
drwxrwxr-x 8 nulee nulee    4096 1月  25 00:30 ..
-rwxr-xr-x 1 nulee nulee 3396768 1月  20 16:48 client_linux_mipsle

./files/ar71xx:
总用量 3328
drwxrwxrwx 2 nulee nulee    4096 1月  25 00:31 .
drwxrwxr-x 8 nulee nulee    4096 1月  25 00:30 ..
-rwxr-xr-x 1 nulee nulee 3396768 1月  20 16:48 client_linux_mips

./files/arm:
总用量 8844
drwxrwxr-x 2 nulee nulee    4096 1月  25 00:32 .
drwxrwxr-x 8 nulee nulee    4096 1月  25 00:30 ..
-rwxr-xr-x 1 nulee nulee 3056112 1月  20 16:47 client_linux_arm5
-rwxr-xr-x 1 nulee nulee 2990552 1月  20 16:47 client_linux_arm6
-rwxr-xr-x 1 nulee nulee 2990552 1月  20 16:47 client_linux_arm7

./files/etc:
总用量 16
drwxrwxrwx 4 nulee nulee 4096 1月   4 10:12 .
drwxrwxr-x 8 nulee nulee 4096 1月  25 00:30 ..
drwxrwxrwx 2 nulee nulee 4096 1月   4 10:12 config
drwxrwxrwx 2 nulee nulee 4096 1月   4 10:12 init.d

./files/etc/config:
总用量 12
drwxrwxrwx 2 nulee nulee 4096 1月   4 10:12 .
drwxrwxrwx 4 nulee nulee 4096 1月   4 10:12 ..
-rwxrwxrwx 1 nulee nulee  303 1月   4 10:12 kcptun

./files/etc/init.d:
总用量 12
drwxrwxrwx 2 nulee nulee 4096 1月   4 10:12 .
drwxrwxrwx 4 nulee nulee 4096 1月   4 10:12 ..
-rwxrwxrwx 1 nulee nulee 1116 1月   4 10:12 kcptun

./files/x86:
总用量 2852
drwxrwxrwx 2 nulee nulee    4096 1月  25 00:28 .
drwxrwxr-x 8 nulee nulee    4096 1月  25 00:30 ..
-rwxr-xr-x 1 nulee nulee 2908832 1月  20 16:45 client_linux_386

./files/x86_64:
总用量 3524
drwxrwxrwx 2 nulee nulee    4096 1月  25 00:27 .
drwxrwxr-x 8 nulee nulee    4096 1月  25 00:30 ..
-rwxr-xr-x 1 nulee nulee 3597568 1月  20 16:45 client_linux_amd64
`
`define Package/$(PKG_NAME)/install
	$(INSTALL_DIR) $(1)/etc/config
	$(INSTALL_DATA) ./files/etc/config/kcptun $(1)/etc/config/kcptun
	$(INSTALL_DIR) $(1)/etc/init.d
	$(INSTALL_BIN) ./files/etc/init.d/kcptun $(1)/etc/init.d/kcptun

	$(INSTALL_DIR) $(1)/usr/bin
ifeq ($(ARCH),mipsel)
	$(INSTALL_BIN) ./files/7620n/client_linux_mipsle $(1)/usr/bin/ssr-kcptun
endif
ifeq ($(ARCH),mips)
	$(INSTALL_BIN) ./files/ar71xx/client_linux_mips $(1)/usr/bin/ssr-kcptun
endif
ifeq ($(ARCH),i386)
	$(INSTALL_BIN) ./files/x86/client_linux_386 $(1)/usr/bin/ssr-kcptun
endif
ifeq ($(ARCH),x86_64)
	$(INSTALL_BIN) ./files/x86_64/client_linux_amd64 $(1)/usr/bin/ssr-kcptun
endif`

这个样子？

**Comment by ywb94** [comment]
不用此章节
define Package/$(PKG_NAME)/install
只需要针对不同平台，将对应的可执行文件拷贝到/usr/bin即可，其他由openwrt-ssr控制
