### ISSUE TITLE
装1.12报错

### ISSUE THREAD

**Issue by bobo-fat** [ywb94/openwrt-ssr#5]
有进程，但接不上
Installing luci-app-shadowsocksR-Server (1.1.2-1) to root...
Configuring luci-app-shadowsocksR-Server.
//usr/lib/opkg/info/luci-app-shadowsocksR-Server.postinst: .: line 7: can't open '/etc/uci-defaults/luci-'
  这什么意思？？谢谢

**Comment by bobo-fat** [comment]
我自己编了x64的，安装报错，好像内核不兼容

**Comment by ywb94** [comment]
1、请把错误信息贴完整
2、启用后ps|grep ss、netstat -nautp|grep ss信息贴出来看看

**Comment by bobo-fat** [comment]
X86的虽然报错，但是搞定了，现在能连接了，但是不能科学上网
