### ISSUE TITLE
1.2.1版检查百度连接异常

### ISSUE THREAD

**Issue by GuangX3** [ywb94/openwrt-ssr#50]
无论开不开代理，百度的连接检查都显示connect error

ping是可以ping通的：

正在 Ping www.baidu.com [183.232.231.172] 具有 32 字节的数据:
来自 183.232.231.172 的回复: 字节=32 时间=13ms TTL=55
来自 183.232.231.172 的回复: 字节=32 时间=10ms TTL=55
来自 183.232.231.172 的回复: 字节=32 时间=10ms TTL=55
来自 183.232.231.172 的回复: 字节=32 时间=10ms TTL=55

**Comment by GuangX3** [comment]
已经找到原因，在Network->Wireless删除无线后会出现此问题

**Comment by GuangX3** [comment]
我重新刷了固件（不保留任何配置），系统是干净的，装完这个IPK，点击检查百度，还是提示连接错误，虽然实际上百度以及国内网站访问正常

Log如下:

Wed Jan 25 19:40:10 2017 daemon.err uhttpd[860]: /usr/bin/ssr-check: line 1: ELF@@4p4: not found
Wed Jan 25 19:40:10 2017 daemon.err uhttpd[860]: /usr/bin/ssr-check: line 2: 44@4@@@tt@t@p??@?@p??@?@@@????A?A????@?@@@Q?tdR?td??A?A: not found
Wed Jan 25 19:40:10 2017 daemon.err uhttpd[860]: /usr/bin/ssr-check: line 2: /lib/ld-musl-mipsel-sf.so.1: not found
Wed Jan 25 19:40:10 2017 daemon.err uhttpd[860]: /usr/bin/ssr-check: line 3: ?p: not found
Wed Jan 25 19:40:10 2017 daemon.err uhttpd[860]: /usr/bin/ssr-check: line 6: syntax error: unexpected "(

**Comment by ywb94** [comment]
我这边没有此问题，你的日志信息显示你好像装错了ipk（安装了其他平台的ipk），可以运行
/usr/bin/ssr-check www.baidu.com 80 1
看提示什么信息
或者将1.2.1中的/usr/bin/ssr-check替换为1.2.0中的/usr/bin/ssr-check

**Comment by GuangX3** [comment]
你好，经过检查确实是我编译时出错，在ar7xxx的平台上装了MT7620 SDK编译的ipk，安装时没有报错所以没发现。

重新编译安装后使用正常，非常感谢！
