### ISSUE TITLE
client 1.2.1 无法切换服务器

### ISSUE THREAD

**Issue by Copox** [ywb94/openwrt-ssr#51]
1.2.1于luci中切换服务器，无法立刻生效，需要重启才能切换到服务器，如今已经换回1.2.0，功能一切正常

**Comment by ywb94** [comment]
“无法立刻生效”指的是切换后无法上网？请查看openwrt“系统日志”是否有错误信息，服务器配置是否正确？
我这边试了下，切换是没有问题的。

**Comment by Copox** [comment]
网络正常，只是无法切换服务器，就算luci界面中显示其他服务器，可是使用的却是不变，唯有重启前先换到目标服务器，重启后才正确换到，不知道跟什么有关系。因为每次升级都会覆盖旧版的配置文件，而不是改名，所以通才本人都会手动备份旧的等更新完后覆盖上去，难道跟配置文件有关系？

**Comment by ywb94** [comment]
不建议覆盖配置文件，你新建试试

**Comment by Copox** [comment]
经排查，是配置文件问题，那么这样就麻烦了，每次升级都会清掉配置，意味着又要手动填写，对于多服务器来说是非常繁琐的一件事情

**Comment by ywb94** [comment]
后续考虑配置的保存与恢复

**Comment by Copox** [comment]
好的，谢谢作者
