### ISSUE TITLE
kcp始终连不上,大大帮我看看

### ISSUE THREAD

**Issue by genics** [ywb94/openwrt-ssr#53]
2017/01/26 06:07:04 version: 20170120
2017/01/26 06:07:04 listening on: [::]:11981
2017/01/26 06:07:04 encryption: salsa20
2017/01/26 06:07:04 nodelay parameters: 1 20 2 1
2017/01/26 06:07:04 remote address: 45.63.121.246:38989
2017/01/26 06:07:04 sndwnd: 2048 rcvwnd: 1024
2017/01/26 06:07:04 compression: false
2017/01/26 06:07:04 mtu: 1350
2017/01/26 06:07:04 datashard: 10 parityshard: 3
2017/01/26 06:07:04 acknodelay: false
2017/01/26 06:07:04 dscp: 0
2017/01/26 06:07:04 sockbuf: 4194304
2017/01/26 06:07:04 keepalive: 10
2017/01/26 06:07:04 conn: 1
2017/01/26 06:07:04 autoexpire: 0
2017/01/26 06:07:04 snmplog: 
2017/01/26 06:07:04 snmpperiod: 60

**Comment by ywb94** [comment]
你直接用/usr/bin/ssr-kcptun加命令行参数看能不能连接，连接不上的话需检查配置或找kcptun作者

**Comment by kukudemajia** [comment]
我也遇到这个问题，我的ac68u和pc客户端用kcptun就没问题

**Comment by ywb94** [comment]
参照kcp官方的参数（https://github.com/xtaci/kcptun）在命令行输入，或在luci的“KcpTun”中输入
