### ISSUE TITLE
老大，AMD64平台下总是编译不了

### ISSUE THREAD

**Issue by kukudemajia** [ywb94/openwrt-ssr#54]
OpenWrt-SDK-15.05.1-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2
OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2
在ubuntu 64位系统，16.10 16.04都无法编译成功
求解，谢谢
root@lcc-VirtualBox:/home/lcc/ss/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64# make package/openwrt-ssr/compile -j1 V=s
#
# configuration written to .config
#
make[1]: Entering directory '/home/lcc/ss/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64'
make[2]: Entering directory '/home/lcc/ss/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/feeds/packages/libs/pcre'
if [ -f /home/lcc/ss/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/target-x86_64_uClibc-0.9.33.2/pkginfo/pcre.default.install.clean ]; then rm -f /home/lcc/ss/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/target-x86_64_uClibc-0.9.33.2/pkginfo/pcre.default.install /home/lcc/ss/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/target-x86_64_uClibc-0.9.33.2/pkginfo/pcre.default.install.clean; fi; echo "libpcre" >> /home/lcc/ss/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/target-x86_64_uClibc-0.9.33.2/pkginfo/pcre.default.install
make[2]: Leaving directory '/home/lcc/ss/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/feeds/packages/libs/pcre'
make[2]: Entering directory '/home/lcc/ss/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/package/openwrt-ssr'
if [ -f /home/lcc/ss/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/target-x86_64_uClibc-0.9.33.2/pkginfo/openwrt-ssr.openssl.install.clean ]; then rm -f /home/lcc/ss/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/target-x86_64_uClibc-0.9.33.2/pkginfo/openwrt-ssr.openssl.install /home/lcc/ss/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/target-x86_64_uClibc-0.9.33.2/pkginfo/openwrt-ssr.openssl.install.clean; fi; echo "luci-app-shadowsocksR-GFW" >> /home/lcc/ss/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/target-x86_64_uClibc-0.9.33.2/pkginfo/openwrt-ssr.openssl.install
make[2]: Leaving directory '/home/lcc/ss/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/package/openwrt-ssr'
make[1]: Leaving directory '/home/lcc/ss/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64'

**Comment by ywb94** [comment]
错误信息没显示出来

**Comment by kukudemajia** [comment]
所以就不知道到底问题是在哪里了？看起来都正常，不过后来我直接下载你编译的客户端就没问题了，但是KCPTUN有问题，连不上，SS正常，服务器正常，因为在别的路由器上正常，同样的设置
