### ISSUE TITLE
集成固件编译  BUG

### ISSUE THREAD

**Issue by zaion520** [ywb94/openwrt-ssr#55]
GFW  /etc/dnsmasq.conf  会少'conf-dir=/etc/dnsmasq.ssr '
单独安装则没有问题

**Comment by ywb94** [comment]
估计是固件集成时先make安装了ssr，再安装的dnsmasq-full，可能要调整下make顺序

**Comment by ywb94** [comment]
我将GFW版本编译进netgear wndr3800的固件试了下，好像没有这个问题

**Comment by ywb94** [comment]
最新源码已修改，不动/etc/dnsmasq.conf了
