### ISSUE TITLE
kcp无法连接，在别的路由器和PC端正常

### ISSUE THREAD

**Issue by kukudemajia** [ywb94/openwrt-ssr#56]
KCP在华硕AC68U和PC客户端使用正常
设置应该没问题，SS正常，但是开启KCP就不行
PK 版本号
1.2.1
KcpTun 版本号
20170120
为什么udp始终是直连SS服务器呢？即使是设置了KCP

**Comment by ywb94** [comment]
ss和kcp是不是同一个服务器？

**Comment by kukudemajia** [comment]
SS和KCP是在同一个服务器上的

KCPTUN的参数：
{
    "listen": "0.0.0.0:29900",改为服务器IP也没有用
    "target": "127.0.0.1:8666",
    "key": "xxxxxxxxxxxxxxxxxxxx",
    "crypt": "aes",
    "mode": "fast",
    "mtu": 1350,
    "sndwnd": 1024,
    "rcvwnd": 1024,
    "datashard": 10,
    "parityshard": 3,
    "dscp": 0,
    "nocomp": false,
    "acknodelay": false,
    "nodelay": 0,
    "interval": 20,
    "resend": 2,
    "nc": 1,
    "sockbuf": 4194304,
    "keepalive": 10,
    "log": "/var/log/kcptun/server.log"
}

SS的参数：

{
	"server":"0.0.0.0",改为服务器IP也没有用
	"server_port":8666,
	"local_port":1080,
	"password":"xxxxxxxxxxxxxxxxxxxxxxx",
	"timeout":600,
	"method":"rc4-md5"

}

**Comment by kukudemajia** [comment]
![qq 20170203012405](https://cloud.githubusercontent.com/assets/17118600/22560466/b22c987a-e9af-11e6-858d-e737ef86d1fb.jpg)
![qq 20170203012337](https://cloud.githubusercontent.com/assets/17118600/22560473/b5f0b64e-e9af-11e6-8796-675631acc096.jpg)

**Comment by kukudemajia** [comment]
![qq 20170203012932](https://cloud.githubusercontent.com/assets/17118600/22560617/40f0bf46-e9b0-11e6-95c9-23842f781e8e.jpg)

**Comment by kukudemajia** [comment]
IP路由模式和GFW列表模式，还有改成8.8.8.8:53的DNS服务器也没有用

**Comment by kukudemajia** [comment]
![qq 20170203014316](https://cloud.githubusercontent.com/assets/17118600/22561190/268f24b0-e9b2-11e6-95dd-4f9bb5c4113a.jpg)

以上抹去都是服务器IP、端口号以及密码，设置无误

**Comment by kukudemajia** [comment]
KCP服务器版本跟客户端版本一致，客户端换了低版本也是如此，没有改观

**Comment by genics** [comment]
和我一样的情况

**Comment by ywb94** [comment]
1、你说的在路由器上正常的kcp可执行文件和ssr路由器上的可执行文件是否一致？
2、ssr只是单纯调用kcp的命令行执行，没有进行其他处理。我看你的命令行参数都是加“-”，而在官网都是要求加“--”，你将“-”改为“--”试试
3、我以前使用时发现用压缩方式存在问题，你将kcp服务器和客户端改为非压缩试试
4、看看openwrt的"系统日志"中有无异常信息

**Comment by kukudemajia** [comment]
1、路由器上正常的kcp可执行文件和ssr路由器上的可执行文件版本是一致的，但是平台不一样，ssr路由器是在esxi跑的x64 openwrt；
2、kcp的命令都是系统自动运行的，不是我手打的
后面的问题晚点才能回复

**Comment by ywb94** [comment]
kcp的命令不是系统自动运行的，是你在ssr的luci界面配置的“KcpTun参数”

**Comment by kukudemajia** [comment]
现在明白了，3Q，我试试看，这些参数在手机app、AC68U路由器、PC客户端都没问题
刚试过了 KcpTun参数  --autoexpire 60 --key "xxxxxxxxxx" 还是一样不行

**Comment by kukudemajia** [comment]
Sun Feb  5 15:56:05 2017 user.emerg syslog: service: file '/usr/bin/ssr-monitor' is not executable
日志看到这个

**Comment by kukudemajia** [comment]
Sun Feb  5 15:56:05 2017 daemon.info dnsmasq[1965]: using nameserver 8.8.8.8#53
Sun Feb  5 15:56:05 2017 daemon.info dnsmasq[1965]: read /etc/hosts - 1 addresses
Sun Feb  5 15:56:05 2017 daemon.info dnsmasq[1965]: read /tmp/hosts/dhcp - 1 addresses
Sun Feb  5 15:56:05 2017 user.emerg syslog: service: file '/usr/bin/ssr-monitor' is not executable
Sun Feb  5 15:56:05 2017 daemon.info procd: - init complete -
Sun Feb  5 15:56:06 2017 kern.info kernel: [   11.162726] br-lan: port 1(eth0) entered forwarding state
Sun Feb  5 15:56:32 2017 kern.info /usr/bin/ssr-tunnel[2199]: tcp port reuse enabled
Sun Feb  5 15:56:32 2017 kern.info /usr/bin/ssr-tunnel[2199]: UDP relay enabled
Sun Feb  5 15:56:32 2017 kern.info /usr/bin/ssr-tunnel[2199]: udp port reuse enabled
Sun Feb  5 15:56:32 2017 kern.info /usr/bin/ssr-tunnel[2199]: listening at 0.0.0.0:5353
Sun Feb  5 15:56:32 2017 kern.info /usr/bin/ssr-tunnel[2199]: running from root user
Sun Feb  5 15:56:32 2017 kern.info /usr/bin/ssr-redir[2189]: UDP relay enabled
Sun Feb  5 15:56:32 2017 kern.info /usr/bin/ssr-redir[2189]: udp port reuse enabled
Sun Feb  5 15:56:32 2017 kern.info /usr/bin/ssr-redir[2189]: TCP relay disabled
Sun Feb  5 15:56:32 2017 kern.info /usr/bin/ssr-redir[2189]: listening at 0.0.0.0:1234
Sun Feb  5 15:56:32 2017 kern.info /usr/bin/ssr-redir[2189]: running from root user
Sun Feb  5 15:56:32 2017 kern.info /usr/bin/ssr-redir[2161]: tcp port reuse enabled
Sun Feb  5 15:56:32 2017 kern.notice kernel: [   37.140270] random: nonblocking pool is initialized
Sun Feb  5 15:56:57 2017 kern.info /usr/bin/ssr-redir[2549]: initializing ciphers... rc4-md5
Sun Feb  5 15:56:57 2017 kern.info /usr/bin/ssr-redir[2549]: tcp port reuse enabled
Sun Feb  5 15:56:57 2017 kern.info /usr/bin/ssr-redir[2549]: listening at 0.0.0.0:1234
Sun Feb  5 15:56:57 2017 kern.info /usr/bin/ssr-redir[2549]: running from root user
Sun Feb  5 15:56:57 2017 kern.info /usr/bin/ssr-redir[2577]: initializing ciphers... rc4-md5
Sun Feb  5 15:56:57 2017 kern.info /usr/bin/ssr-redir[2577]: UDP relay enabled
Sun Feb  5 15:56:57 2017 kern.info /usr/bin/ssr-redir[2577]: udp port reuse enabled
Sun Feb  5 15:56:57 2017 kern.info /usr/bin/ssr-redir[2577]: TCP relay disabled
Sun Feb  5 15:56:57 2017 kern.info /usr/bin/ssr-redir[2577]: listening at 0.0.0.0:1234
Sun Feb  5 15:56:57 2017 kern.info /usr/bin/ssr-redir[2577]: running from root user
Sun Feb  5 15:56:57 2017 kern.info /usr/bin/ssr-tunnel[2589]: initializing ciphers... rc4-md5
Sun Feb  5 15:56:57 2017 kern.info /usr/bin/ssr-tunnel[2589]: tcp port reuse enabled
Sun Feb  5 15:56:57 2017 kern.info /usr/bin/ssr-tunnel[2589]: UDP relay enabled
Sun Feb  5 15:56:57 2017 kern.info /usr/bin/ssr-tunnel[2589]: udp port reuse enabled
Sun Feb  5 15:56:57 2017 kern.info /usr/bin/ssr-tunnel[2589]: listening at 0.0.0.0:5353
Sun Feb  5 15:56:57 2017 kern.info /usr/bin/ssr-tunnel[2589]: running from root user
Sun Feb  5 16:00:43 2017 kern.info /usr/bin/ssr-redir[3269]: initializing ciphers... rc4-md5
Sun Feb  5 16:00:43 2017 kern.info /usr/bin/ssr-redir[3269]: tcp port reuse enabled
Sun Feb  5 16:00:43 2017 kern.info /usr/bin/ssr-redir[3269]: UDP relay enabled
Sun Feb  5 16:00:43 2017 kern.info /usr/bin/ssr-redir[3269]: udp port reuse enabled
Sun Feb  5 16:00:43 2017 kern.info /usr/bin/ssr-redir[3269]: listening at 0.0.0.0:1234
Sun Feb  5 16:00:43 2017 kern.info /usr/bin/ssr-redir[3269]: running from root user
Sun Feb  5 16:00:43 2017 kern.info /usr/bin/ssr-tunnel[3281]: initializing ciphers... rc4-md5
Sun Feb  5 16:00:43 2017 kern.info /usr/bin/ssr-tunnel[3281]: tcp port reuse enabled
Sun Feb  5 16:00:43 2017 kern.info /usr/bin/ssr-tunnel[3281]: UDP relay enabled
Sun Feb  5 16:00:43 2017 kern.info /usr/bin/ssr-tunnel[3281]: udp port reuse enabled
Sun Feb  5 16:00:43 2017 kern.info /usr/bin/ssr-tunnel[3281]: listening at 0.0.0.0:5353
Sun Feb  5 16:00:43 2017 kern.info /usr/bin/ssr-tunnel[3281]: running from root user
Sun Feb  5 16:01:20 2017 kern.info /usr/bin/ssr-redir[3577]: initializing ciphers... rc4-md5
Sun Feb  5 16:01:20 2017 kern.info /usr/bin/ssr-redir[3577]: tcp port reuse enabled
Sun Feb  5 16:01:20 2017 kern.info /usr/bin/ssr-redir[3577]: listening at 0.0.0.0:1234
Sun Feb  5 16:01:20 2017 kern.info /usr/bin/ssr-redir[3577]: running from root user
Sun Feb  5 16:01:20 2017 kern.info /usr/bin/ssr-redir[3605]: initializing ciphers... rc4-md5
Sun Feb  5 16:01:20 2017 kern.info /usr/bin/ssr-redir[3605]: UDP relay enabled
Sun Feb  5 16:01:20 2017 kern.info /usr/bin/ssr-redir[3605]: udp port reuse enabled
Sun Feb  5 16:01:20 2017 kern.info /usr/bin/ssr-redir[3605]: TCP relay disabled
Sun Feb  5 16:01:20 2017 kern.info /usr/bin/ssr-redir[3605]: listening at 0.0.0.0:1234
Sun Feb  5 16:01:20 2017 kern.info /usr/bin/ssr-redir[3605]: running from root user
Sun Feb  5 16:01:20 2017 kern.info /usr/bin/ssr-tunnel[3615]: initializing ciphers... rc4-md5
Sun Feb  5 16:01:20 2017 kern.info /usr/bin/ssr-tunnel[3615]: tcp port reuse enabled
Sun Feb  5 16:01:20 2017 kern.info /usr/bin/ssr-tunnel[3615]: UDP relay enabled
Sun Feb  5 16:01:20 2017 kern.info /usr/bin/ssr-tunnel[3615]: udp port reuse enabled
Sun Feb  5 16:01:20 2017 kern.info /usr/bin/ssr-tunnel[3615]: listening at 0.0.0.0:5353
Sun Feb  5 16:01:20 2017 kern.info /usr/bin/ssr-tunnel[3615]: running from root user

**Comment by kukudemajia** [comment]
--autoexpire 60 --key "xxxxxxxxxx" --nocomp true
已经把kcp服务器和客户端改为非压缩，ssr路由器还是不行，ac68u客户端加上-nocomp true参数后就可以正常访问了

**Comment by kukudemajia** [comment]
![qq 20170205165739](https://cloud.githubusercontent.com/assets/17118600/22624925/4a87f6d0-ebc4-11e6-9a4e-113062b863ad.jpg)

**Comment by ywb94** [comment]
设置为非压缩直接“-nocomp”，不用加true

**Comment by ywb94** [comment]
ssr只是单纯调用kcp的命令行执行，如果有问题，请检查可执行文件和命令行参数是否正确
