### ISSUE TITLE
安装ipk时与ip-full冲突

### ISSUE THREAD

**Issue by etnperlong** [ywb94/openwrt-ssr#57]
Installing luci-app-shadowsocksR-GFW (1.2.1) to root...
Installing ip (4.0.0-1) to root...
Collected errors:
 * check_conflicts_for: The following packages conflict with ip:
 * check_conflicts_for:         ip-full *
 * opkg_install_cmd: Cannot install package luci-app-shadowsocksR-GFW.

**Comment by ywb94** [comment]
https://github.com/ywb94/openwrt-ssr/issues/14
