### ISSUE TITLE
mt7628编译失败

### ISSUE THREAD

**Issue by mineyosemite** [ywb94/openwrt-ssr#59]
谁能编译一个mt7628的ssr,谢谢

**Comment by mineyosemite** [comment]
https://github.com/ywb94/openwrt-ssr/issues/29就 是遇到了这位人士的问题，求问如何配置编译环境。鄙人初识编译，还请指教，谢谢

**Comment by ywb94** [comment]
Ubuntu 64位系统先安装如下依赖包试试：
sudo apt-get install build-essential asciidoc binutils bzip2 gawk gettext  git libncurses5-dev libz-dev patch unzip zlib1g-dev  subversion git ccache
