### ISSUE TITLE
安装好了，能连接上网，但是不科学

### ISSUE THREAD

**Issue by bobo-fat** [ywb94/openwrt-ssr#6]
http://www.right.com.cn/forum/thread-152879-1-2.html
装在这个ROM上的
用的自带的透明代理，在家里的客户端自动科学上网。
装好了ssSERVER端，在外面连接SS后能上网，但是不科学
请问有什么IPTABLES命令可以链接家里的SSSERVER，自动科学上网呢。请指教

**Comment by ywb94** [comment]
不用配置啊，我这里手机接入后可以直接科学上网，你的ssr客户端是不是用的这个，如果不是的话要自己检查有没有冲突（比如dns解析、路由、防火墙规则等），或者你路由上的其他dns或路由转发的软件改变了报文流向
