### ISSUE TITLE
关于dns污染的问题

### ISSUE THREAD

**Issue by Chandler-Lu** [ywb94/openwrt-ssr#60]
在 openwrt-mt7620上使用非gfw版本的ssr，日本节点，除修改了节点信息以外，其他参数默认。经nslookup查询发现google被解析到了加拿大的某个ip上，速度严重下降。安装pdnsd后也没有发现开发者说的那个dns解析方式，不知道是我操作有问题还是？

**Comment by ywb94** [comment]
原始版本本地dns是被污染的，由ssr服务器进行二次解析。
pdnsd控制只有gfw版本支持，原始版本不支持
