### ISSUE TITLE
安装了恩山发布的ramips平台的lede版却无法启动

### ISSUE THREAD

**Issue by haruhitamako** [ywb94/openwrt-ssr#61]
日志如下：

Wed Feb  8 23:40:41 2017 daemon.err uhttpd[774]: sh: /usr/bin/ssr-check: not found
Wed Feb  8 23:40:41 2017 daemon.err uhttpd[774]: sh: /usr/bin/ssr-check: not found
Wed Feb  8 23:41:07 2017 user.notice shadowsocksr: ssr redir tcp error.restart!
Wed Feb  8 23:41:19 2017 daemon.err uhttpd[774]: /etc/rc.common: line 145: /usr/bin/ssr-redir: not found
Wed Feb  8 23:41:49 2017 user.notice shadowsocksr: ssr redir tcp error.restart!
Wed Feb  8 23:42:24 2017 daemon.err uhttpd[774]: sh: /usr/bin/ssr-check: not found
Wed Feb  8 23:42:25 2017 daemon.err uhttpd[774]: sh: /usr/bin/ssr-check: not found
Wed Feb  8 23:42:30 2017 daemon.err uhttpd[774]: sh: /usr/bin/ssr-check: not found
Wed Feb  8 23:42:31 2017 daemon.err uhttpd[774]: sh: /usr/bin/ssr-check: not found
Wed Feb  8 23:42:32 2017 daemon.err uhttpd[774]: sh: /usr/bin/ssr-check: not found
Wed Feb  8 23:43:17 2017 user.notice shadowsocksr: ssr redir tcp error.restart!
Wed Feb  8 23:43:48 2017 user.notice shadowsocksr: ssr redir tcp error.restart!
Wed Feb  8 23:44:20 2017 user.notice shadowsocksr: ssr redir tcp error.restart!
Wed Feb  8 23:44:52 2017 user.notice shadowsocksr: ssr redir tcp error.restart!
Wed Feb  8 23:45:23 2017 user.notice shadowsocksr: ssr redir tcp error.restart!

**Comment by ywb94** [comment]
我用K2（MT7620A）刷LEDE 17.01-RC1，然后安装SSR GFW版本，是没有问题的。
请检查你是否安装了正确的SSR GFW版本，如果还不行，请刷新LEDE版本到LEDE 17.01-RC1

**Comment by haruhitamako** [comment]
@ywb94 我使用的是k1的lede-rc1。ssr使用的是ip路由的原始版本

**Comment by haruhitamako** [comment]
噢，问题在我身上，装错版本了
