### ISSUE TITLE
lede集成编译问题

### ISSUE THREAD

**Issue by ztzkao** [ywb94/openwrt-ssr#62]
在lede集成编译后，luci界面无法添加配置文件。

**Comment by ywb94** [comment]
你说的集成编译是集成到固件中么？我这里试安装IPK是没有这个问题的

**Comment by ztzkao** [comment]
集成编译的话会不能添加🤔

**Comment by ywb94** [comment]
在openwrt中集成编译到固件是没有问题的，lede试过交叉编译是没有问题的，集成编译应该也不会有问题。
如果你那边有问题，你可以试试用SDK交叉编译IPK看看会不会也出现同样的问题
