### ISSUE TITLE
luci要是能加个延迟测试就好了！！

### ISSUE THREAD

**Issue by daofeng2015** [ywb94/openwrt-ssr#63]
看别人的SS的luci有测试服务器的延迟功能，能否也做一个呢？？

**Comment by ywb94** [comment]
很简单啊，在服务器端口检查时加ping，然后获取延时值

**Comment by ywb94** [comment]
![image](https://cloud.githubusercontent.com/assets/24707363/22873510/904fac02-f1fb-11e6-9b60-86ae337f6a33.png)
是不是这样的效果？

**Comment by daofeng2015** [comment]
这样也行
