### ISSUE TITLE
过几天准备用你的了。不知道和pcap_dnsproxy配合如何？

### ISSUE THREAD

**Issue by zasl** [ywb94/openwrt-ssr#64]
因地区原因封锁比较厉害，pcap效果好于pdnsd，所以想问下这个和pcap配合如何？这个非常需要

**Comment by jingkelinlin** [comment]
对不起…我是个新手正在学习…帮不上你的忙！抱歉！

2017年2月16日 22:12，"zasl" <notifications@github.com>写道：

**Comment by ywb94** [comment]
没用过，你可以试试，记得要用原始版本

**Comment by 467815891a** [comment]
试了是可以的，但是感觉Pcap-DNSproxy虽然解析速度快，但是太占内存了，我这边是pdnsd的3倍，本来pdnsd就有点占内存了，所以在路由器上使用还是pdnsd好。另外一个重要原因是pcap-DNSproxy经常造成网页无法访问，但是dig或者nslookup之后又发现解析没有问题，懒得折腾，还是pdnsd好用
