### ISSUE TITLE
想单独编译ip路由客户端

### ISSUE THREAD

**Issue by haruhitamako** [ywb94/openwrt-ssr#65]
如题，我是不是把makefile里面所有有关luci-app-shadowsocksR-Server的字段都删掉？

**Comment by ywb94** [comment]
把下面语句前的#去掉
#$(eval $(call BuildPackage,luci-app-shadowsocksR-Client))
然后在make menuconfig中选择luci-app-shadowsocksR-Client

**Comment by haruhitamako** [comment]
@ywb94 感谢，我尝试一下。

**Comment by haruhitamako** [comment]
@ywb94 使用xz命令解压lede的sdk文件后。使用cd提示lede-sdkxx.tar不是目录文件，还需要继续解压tar文件？

**Comment by haruhitamako** [comment]
@ywb94 请教一下输入make menuconfig后出现的错误是什么？
![qq 20170217220546](https://cloud.githubusercontent.com/assets/24506636/23068191/9dec743e-f55d-11e6-823c-e05692160dc6.png)

**Comment by haruhitamako** [comment]
已经编译成功了。问题在vps的系统上，缺失依赖没提示。换回家里的win10子系统就提示了，把依赖都装上就成功了。感谢作者的项目
