### ISSUE TITLE
开启后就连接不上了

### ISSUE THREAD

**Issue by pxss** [ywb94/openwrt-ssr#73]
我装的是IP模式的IPK，装好完全没问题，就是一配置好，启动SSR时过一会就不能访问路由器的80和22了。求解决

**Comment by ywb94** [comment]
你的路由器lan口的ip是多少

**Comment by pxss** [comment]
172.8.8.1

**Comment by ywb94** [comment]
换一个网段
比如172.16.0.0或者192.0.0.0
