### ISSUE TITLE
安装后QQ可以登陆，网页无法连接网络，请教是什么原因？

### ISSUE THREAD

**Issue by jxmlingyun** [ywb94/openwrt-ssr#76]
查看运行状态都是未运行的，连通性都是有问题。

**Comment by ywb94** [comment]
看不明白，SSR和QQ登陆有什么关系？

**Comment by jxmlingyun** [comment]
我的意思安装好SSR以后，电脑连接路由器，电脑上QQ可以登陆，网页无法连接网络

**Comment by jxmlingyun** [comment]
r oot@LiMe-527404:~#opkg install /tmp/luci-app-shadowsocksR_1.2.1_all.ipk
Installing luci-app-shadowsocksR (1.2.1) to root...
Multiple packages (libpthread and libpthread) providing same name marked HOLD or PREFER. Using latest.
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-shadowsocksR:
 * 	kernel (= 4.4.52-1-30a45372a65abd0700f23402b9b0bbb7) * 	kernel (= 4.4.52-1-30a45372a65abd0700f23402b9b0bbb7) * 	kernel (= 4.4.52-1-30a45372a65abd0700f23402b9b0bbb7) * 
 * opkg_install_cmd: Cannot install package luci-app-shadowsocksR.


root@LiMe-527404:~# opkg install /tmp/luci-app-shadowsocksR_1.2.1_all.ipk --force-depends

还有个问题就是我安装的提示有依赖无法安装，我用force-depends强制安装了，这样会不会有问题？

**Comment by jxmlingyun** [comment]
刚才在路由器又重新安装了一次SSR，还是无法FQ。在“状态”里面看到，各项还是没有运行状态：

全局客户端     未运行
SSR服务端      未运行
UDP中继         未运行
SOCKS5代理    未运行
DNS 隧道        未运行
KcpTun          未运行

【谷歌】连通性检查 检查连通性 连接错误
【百度】连通性检查 检查连通性 连接错误

**Comment by ywb94** [comment]
很有可能是装的版本不对或没有适合你平台的IPK，需重新编译
