### ISSUE TITLE
反馈路由表的问题

### ISSUE THREAD

**Issue by gaoyan1234** [ywb94/openwrt-ssr#78]
装的gfw版 两种模式都正常 但还是有个小问题 这里反馈一下
在路由器下游的lan 一切正常 但是在路由器上装的一些vpn服务器貌似不走代理。比如我在路由器上装了pptpd openvpn 当从上游的局域网连接到这个路由器后  就没法翻外网了 感觉应该是iptables的一些参数的问题

**Comment by ywb94** [comment]
没考虑过ssr和vpn混用，我一般分开用。

ssr通过iptables控制，VPN通过路由表控制

**Comment by gaoyan1234** [comment]
我导出路由表看了一下 有下面两条规则：
-I PREROUTING 1 **-i br-lan** -p tcp -m comment --comment _SS_SPEC_RULE_ -j SS_SPEC_WAN_AC
-I PREROUTING 1 **-i br-lan** -p udp -m comment --comment _SS_SPEC_RULE_ -j SS_SPEC_TPROXY

只要删掉 **-i br-lan** 这样不仅lan端口可以智能翻 ，路由器的所有端口包含vpn服务器 就都可以（@ywb94  原来是为了控制内网哪些主机可以访问代理的）

请问@ywb94  可否告知如何从源码中删除  **-i br-lan**  省的我每次都要自己改
或者在“路由器访问控制” 加上这个选项 让用户选择
谢谢

**Comment by ywb94** [comment]
修改shadowsocksr.rule文件删除
${IFNAME:+-i $IFNAME}

**Comment by gaoyan1234** [comment]
谢谢
