### ISSUE TITLE
电脑能正常番茄，但手机像有dns污染，打不开谷歌全家和脸书

### ISSUE THREAD

**Issue by haruhitamako** [ywb94/openwrt-ssr#8]
如题

**Comment by haruhitamako** [comment]
确认手机端dns被污染，在wifi设置google dns后番茄正常。希望可以解决这个问题

**Comment by ywb94** [comment]
此版本设计的就是不处理本地dns污染，由远端服务器解析。刷新dns缓存后应该能上

后面准备开个gfwlist的版本

**Comment by haruhitamako** [comment]
@ywb94 pc和win平板都是正常的，但是安卓手机连接上去都受到不同程度的污染，手机重启无法解决。不知道远端更改为opendns的抗污染能力会不会增强，毕竟googledns在天朝水土不服
