### ISSUE TITLE
LEDE编译集成ssr的时候报错

### ISSUE THREAD

**Issue by 0x5826** [ywb94/openwrt-ssr#90]
onfiguring fdisk.
Configuring kmod-usb-ledtrig-usbport.
Configuring kmod-usb-uhci.
Configuring kmod-usb-storage-extras.
Configuring mount-utils.
Configuring luci-i18n-firewall-zh-cn.
Configuring ppp-mod-pppoe.
Configuring kmod-ledtrig-netdev.
Collected errors:
 * check_data_file_clashes: Package dnsmasq-full wants to install file /home/zgl/LEDE_last/build_dir/target-mips_24kc_musl/root-ar71xx/etc/hotplug.d/ntp/25-dnsmasqsec
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /home/zgl/LEDE_last/build_dir/target-mips_24kc_musl/root-ar71xx/etc/init.d/dnsmasq
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /home/zgl/LEDE_last/build_dir/target-mips_24kc_musl/root-ar71xx/usr/sbin/dnsmasq
	But that file is already provided by package  * dnsmasq
 * opkg_install_cmd: Cannot install package dnsmasq-full.
 * check_data_file_clashes: Package dnsmasq-full wants to install file /home/zgl/LEDE_last/build_dir/target-mips_24kc_musl/root-ar71xx/etc/hotplug.d/ntp/25-dnsmasqsec
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /home/zgl/LEDE_last/build_dir/target-mips_24kc_musl/root-ar71xx/etc/init.d/dnsmasq
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /home/zgl/LEDE_last/build_dir/target-mips_24kc_musl/root-ar71xx/usr/sbin/dnsmasq
	But that file is already provided by package  * dnsmasq
 * opkg_install_cmd: Cannot install package luci-app-shadowsocksR-GFW.
 * check_data_file_clashes: Package luci-app-shadowsocksR-GFW wants to install file /home/zgl/LEDE_last/build_dir/target-mips_24kc_musl/root-ar71xx/etc/china_ssr.txt
	But that file is already provided by package  * luci-app-shadowsocksR
 * check_data_file_clashes: Package luci-app-shadowsocksR-GFW wants to install file /home/zgl/LEDE_last/build_dir/target-mips_24kc_musl/root-ar71xx/etc/config/shadowsocksr
	But that file is already provided by package  * luci-app-shadowsocksR
 * check_data_file_clashes: Package luci-app-shadowsocksR-GFW wants to install file /home/zgl/LEDE_last/build_dir/target-mips_24kc_musl/root-ar71xx/etc/init.d/shadowsocksr
	But that file is already provided by package  * luci-app-shadowsocksR
 * check_data_file_clashes: Package luci-app-shadowsocksR-GFW wants to install file /home/zgl/LEDE_last/build_dir/target-mips_24kc_musl/root-ar71xx/etc/uci-defaults/luci-shadowsocksr
	But that file is already provided by package  * luci-app-shadowsocksR
 * check_data_file_clashes: Package luci-app-shadowsocksR-GFW wants to install file /home/zgl/LEDE_last/build_dir/target-mips_24kc_musl/root-ar71xx/usr/bin/ssr-check
	But that file is already provided by package  * luci-app-shadowsocksR
 * check_data_file_clashes: Package luci-app-shadowsocksR-GFW wants to install file /home/zgl/LEDE_last/build_dir/target-mips_24kc_musl/root-ar71xx/usr/bin/ssr-local
	But that file is already provided by package  * luci-app-shadowsocksR
 * check_data_file_clashes: Package luci-app-shadowsocksR-GFW wants to install file /home/zgl/LEDE_last/build_dir/target-mips_24kc_musl/root-ar71xx/usr/bin/ssr-monitor
	But that file is already provided by package  * luci-app-shadowsocksR
 * check_data_file_clashes: Package luci-app-shadowsocksR-GFW wants to install file /home/zgl/LEDE_last/build_dir/target-mips_24kc_musl/root-ar71xx/usr/bin/ssr-redir
	But that file is already provided by package  * luci-app-shadowsocksR
 * check_data_file_clashes: Package luci-app-shadowsocksR-GFW wants to install file /home/zgl/LEDE_last/build_dir/target-mips_24kc_musl/root-ar71xx/usr/bin/ssr-rules
	But that file is already provided by package  * luci-app-shadowsocksR
 * check_data_file_clashes: Package luci-app-shadowsocksR-GFW wants to install file /home/zgl/LEDE_last/build_dir/target-mips_24kc_musl/root-ar71xx/usr/bin/ssr-server
	But that file is already provided by package  * luci-app-shadowsocksR
 * check_data_file_clashes: Package luci-app-shadowsocksR-GFW wants to install file /home/zgl/LEDE_last/build_dir/target-mips_24kc_musl/root-ar71xx/usr/bin/ssr-switch
	But that file is already provided by package  * luci-app-shadowsocksR
 * check_data_file_clashes: Package luci-app-shadowsocksR-GFW wants to install file /home/zgl/LEDE_last/build_dir/target-mips_24kc_musl/root-ar71xx/usr/bin/ssr-tunnel
	But that file is already provided by package  * luci-app-shadowsocksR
 * check_data_file_clashes: Package luci-app-shadowsocksR-GFW wants to install file /home/zgl/LEDE_last/build_dir/target-mips_24kc_musl/root-ar71xx/usr/lib/lua/luci/controller/shadowsocksr.lua
	But that file is already provided by package  * luci-app-shadowsocksR
 * check_data_file_clashes: Package luci-app-shadowsocksR-GFW wants to install file /home/zgl/LEDE_last/build_dir/target-mips_24kc_musl/root-ar71xx/usr/lib/lua/luci/i18n/shadowsocksr.zh-cn.lmo
	But that file is already provided by package  * luci-app-shadowsocksR
 * check_data_file_clashes: Package luci-app-shadowsocksR-GFW wants to install file /home/zgl/LEDE_last/build_dir/target-mips_24kc_musl/root-ar71xx/usr/lib/lua/luci/model/cbi/shadowsocksr/client-config.lua
	But that file is already provided by package  * luci-app-shadowsocksR
 * check_data_file_clashes: Package luci-app-shadowsocksR-GFW wants to install file /home/zgl/LEDE_last/build_dir/target-mips_24kc_musl/root-ar71xx/usr/lib/lua/luci/model/cbi/shadowsocksr/client.lua
	But that file is already provided by package  * luci-app-shadowsocksR
 * check_data_file_clashes: Package luci-app-shadowsocksR-GFW wants to install file /home/zgl/LEDE_last/build_dir/target-mips_24kc_musl/root-ar71xx/usr/lib/lua/luci/model/cbi/shadowsocksr/server-config.lua
	But that file is already provided by package  * luci-app-shadowsocksR
 * check_data_file_clashes: Package luci-app-shadowsocksR-GFW wants to install file /home/zgl/LEDE_last/build_dir/target-mips_24kc_musl/root-ar71xx/usr/lib/lua/luci/model/cbi/shadowsocksr/server.lua
	But that file is already provided by package  * luci-app-shadowsocksR
 * check_data_file_clashes: Package luci-app-shadowsocksR-GFW wants to install file /home/zgl/LEDE_last/build_dir/target-mips_24kc_musl/root-ar71xx/usr/lib/lua/luci/model/cbi/shadowsocksr/status.lua
	But that file is already provided by package  * luci-app-shadowsocksR
 * check_data_file_clashes: Package luci-app-shadowsocksR-GFW wants to install file /home/zgl/LEDE_last/build_dir/target-mips_24kc_musl/root-ar71xx/usr/lib/lua/luci/view/shadowsocksr/check.htm
	But that file is already provided by package  * luci-app-shadowsocksR
 * check_data_file_clashes: Package luci-app-shadowsocksR-GFW wants to install file /home/zgl/LEDE_last/build_dir/target-mips_24kc_musl/root-ar71xx/usr/lib/lua/luci/view/shadowsocksr/checkport.htm
	But that file is already provided by package  * luci-app-shadowsocksR
 * check_data_file_clashes: Package luci-app-shadowsocksR-GFW wants to install file /home/zgl/LEDE_last/build_dir/target-mips_24kc_musl/root-ar71xx/usr/lib/lua/luci/view/shadowsocksr/refresh.htm
	But that file is already provided by package  * luci-app-shadowsocksR
 * opkg_install_cmd: Cannot install package luci-app-shadowsocksR-GFW.
make[2]: *** [package/install] Error 255
make[2]: Leaving directory `/home/zgl/LEDE_last'
make[1]: *** [/home/zgl/LEDE_last/staging_dir/target-mips_24kc_musl/stamp/.package_install] Error 2
make[1]: Leaving directory `/home/zgl/LEDE_last'
make: *** [world] 错误 2

**Comment by daiaji** [comment]
会不会是ROOT用户的锅呢？

**Comment by daofeng2015** [comment]
你个二货，你勾选了dnsmasq和dnsmasq-full，当然报错啊，去掉dnsmasq啊

**Comment by laudukang** [comment]
哈哈

**Comment by MrNickLock** [comment]
妈耶，还真是，我也遇到了。默认居然都选了 ，在 Base system 选项下。
