### ISSUE TITLE
潘多拉16.10安装预编译ramips报错

### ISSUE THREAD

**Issue by miyouzi** [ywb94/openwrt-ssr#95]
路由是斐讯K2，使用ramips预编译包。
安装时提示以下无法安装

[root@MIYOUZI_PandoraBox:/root]#opkg install http://10.0.3.10/luci-app-shadowsocksR_1.2.1_all.ipk
Downloading http://10.0.3.10/luci-app-shadowsocksR_1.2.1_all.ipk.
Installing luci-app-shadowsocksR (1.2.1) to root...
Multiple packages (libpthread and libpthread) providing same name marked HOLD or PREFER. Using latest.
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-shadowsocksR:
 *      kernel (= 3.14.79-1) *
 * opkg_install_cmd: Cannot install package luci-app-shadowsocksR.
[root@MIYOUZI_PandoraBox:/root]#opkg remove dnsmasq
Removing package dnsmasq from root...
[root@MIYOUZI_PandoraBox:/root]#opkg install http://10.0.3.10/luci-app-shadowsocksR-GFW_1.2.1_all.ipk
Downloading http://10.0.3.10/luci-app-shadowsocksR-GFW_1.2.1_all.ipk.
Installing luci-app-shadowsocksR-GFW (1.2.1) to root...
Multiple packages (libpthread and libpthread) providing same name marked HOLD or PREFER. Using latest.
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-shadowsocksR-GFW:
 *      kernel (= 3.14.79-1) *  kernel (= 3.14.79-1) *

**Comment by daiaji** [comment]
别装了 装了也没用
潘多拉有BUG
用非GFW版本

**Comment by miyouzi** [comment]
嗯嗯。好的。
